### ISSUE TITLE
Upgrade CodeAnalysis.Testing.ReferenceAssemblies to .Net 7.0 preview 7

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/roslyn-sdk#1006]
Could we upgrade CodeAnalysis.Testing.ReferenceAssemblies to .Net 7.0 preview 7 or at least preview 5?

New APIs needed for testing new analyzers with new attributes/APIs, for example a list of new APIs needed for https://github.com/dotnet/runtime/issues/69775

CC @mavasani @jmarolf @sharwell

**Comment by JoeRobich** [comment]
Opened a PR to update to the Preview 7 packages.

**Comment by buyaa-n** [comment]
Thanks @JoeRobich, I need to reference it in roslyn-analyzers repo. Could we include that with this effort or should I create an issue in roslyn-analyzers repo?

**Comment by JoeRobich** [comment]
Sure. Once the PR is merged and a new build is available, I will update the MicrosoftCodeAnalysisTestingVersion in the roslyn-analyzers eng/Versions.props file.

**Comment by JoeRobich** [comment]
Opened https://github.com/dotnet/roslyn-analyzers/pull/6123 to update roslyn-analyzers to a new build with this change.

**Comment by JoeRobich** [comment]
@buyaa-n roslyn-analyzers repo has been updated.

**Comment by buyaa-n** [comment]
Thanks you!
