### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.XUnit should update its VS-MEF dependency

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-sdk#1053]
The analyzer test library references VS-MEF 16.1, which is quite old. Breaking changes have occurred between that version and 17.x, such that analyzer tests are failing at runtime when the newer version of the assembly is present:

>  System.MissingMethodException : Method not found: 'Void Microsoft.VisualStudio.Composition.ComposablePartDefinition..ctor(Microsoft.VisualStudio.Composition.Reflection.TypeRef, System.Collections.Generic.IReadOnlyDictionary\`2<System.String,System.Object>, System.Collections.Generic.IReadOnlyCollection\`1<Microsoft.VisualStudio.Composition.ExportDefinition>, System.Collections.Generic.IReadOnlyDictionary\`2<Microsoft.VisualStudio.Composition.Reflection.MemberRef,System.Collections.Generic.IReadOnlyCollection\`1<Microsoft.VisualStudio.Composition.ExportDefinition>>, System.Collections.Generic.IEnumerable\`1<Microsoft.VisualStudio.Composition.ImportDefinitionBinding>, System.String, Microsoft.VisualStudio.Composition.Reflection.MethodRef, Microsoft.VisualStudio.Composition.Reflection.MethodRef, System.Collections.Generic.IReadOnlyList\`1<Microsoft.VisualStudio.Composition.ImportDefinitionBinding>, Microsoft.VisualStudio.Composition.CreationPolicy, System.Collections.Generic.IEnumerable\`1<System.Reflection.AssemblyName>, Boolean)'.

Can the analyzer test project upgrade its reference (and revise the overload it's calling)?

**Comment by AArnott** [comment]
CC: @sharwell

**Comment by sharwell** [comment]
Unfortunately it is not possible to update. Microsoft.VisualStudio.Composition 16.1 is the last version which supported all the frameworks supported by this test library.

**Comment by AArnott** [comment]
It looks like your test package supports several TFMs that Microsoft no longer supports. If you're willing to drop them, we'll try to meet you in the middle and add support back for net462, which I think is the oldest supported runtime. Would that work?

**Comment by AArnott** [comment]
It looks like Microsoft.CodeAnalysis packages don't support anything older than vs-mef supports anyway, so why would the test package need to support them?

**Comment by sharwell** [comment]
@AArnott The test library supports analyzer testing for Roslyn 1.3+ (Visual Studio 2015, .NET 4.5.2) and everything newer.

**Comment by AArnott** [comment]
Targeting the 1.3 compiler is fine, I suppose. But your test package itself won't be running on net452, right? I mean, customers should all have net462 or later at this point, even if they are still running the 1.3 compiler version.

**Comment by AArnott** [comment]
Ping on this. It's becoming a bigger problem for us.

**Comment by sharwell** [comment]
We cannot make any changes to this repository until we figure out why CI images no longer allow us to run integration tests.

Current trial and error PR is https://github.com/dotnet/roslyn-sdk/pull/1052
