### ISSUE TITLE
SpecialType property is 'None' instead of 'System_Nullable_T' for INamedTypeSymbol when nullable type

### ISSUE THREAD

**Issue by sergiojrdotnet** [dotnet/roslyn-sdk#1066]
When evaluating a `INamedTypeSymbol` for any nullable type, the `SpecialType` property is always `None` instead `System_Nullable_T`

![image](https://user-images.githubusercontent.com/72770006/221444279-7714ac8f-9ed1-4a38-9718-37f4b624ab9a.png)

**Comment by sharwell** [comment]
This is expected. `System_Nullable_T` refers to `System.Nullable<>`, but `bool?` refers to `System.Nullable<bool>`.
