### ISSUE TITLE
Cannot use raw interpolated string with multiple dollar signs in test code

### ISSUE THREAD

**Issue by reduckted** [dotnet/roslyn-sdk#1067]
I'm trying to test an analyzer by using test code that looks like this:

```cs
int number = 1;
string text = $$"""raw string {{number}}""";
```

Unfortunately, the `$$` is interpreted as a position marker, so the test code that ends up being used is:

```cs
int number = 1;
string text = """raw string {{number}}""";
```

Is there a way to escape a position marker?

**Comment by sharwell** [comment]
No, but you can disable markup for a specific test.
