### ISSUE TITLE
Analyzer as nuget package does not create editor hints in VisualStudio ?

### ISSUE THREAD

**Issue by bramerdaniel** [dotnet/roslyn-sdk#1072]
I am working on a project that contains also a DiagnosticAnalyser. 
Disributed as nuget package it seems to work, but it does not generate the squiggly editor marks in the VisualStudio editor,
I tried to pack it into a visual studio extension, here it works fine. 
Having that problem, codefixes do not work as well, when shipped as npkg.

I also tried existing analyzers/codefixes (xunit + xunit.analyzers ) with the same result.
I tried to google this problem, but could not find any usefull hints.

Is this not working in general, or am I the only one having that problem ?

**Comment by sharwell** [comment]
Are you able to create a sample project to demonstrate this issue? Another option would be to show a NuGet package that reproduces this issue.

**Comment by bramerdaniel** [comment]
I just created a xunit test project and added one test method that causes an analyser problem.

![AnalyserProblem](https://user-images.githubusercontent.com/17742871/226742677-da832860-8519-463a-a780-aa5a846865bf.png)

Here is a screenshot of my studio.

**Comment by bramerdaniel** [comment]
Here is the zipped project 
[XUnitTest.zip](https://github.com/dotnet/roslyn-sdk/files/11033752/XUnitTest.zip)
