### ISSUE TITLE
Nullability annotations are wrong

### ISSUE THREAD

**Issue by tom-englert** [dotnet/roslyn-sdk#1081]
Both `TestCode `and `FixedCode` properties accept null, but are marked as not-null

https://github.com/dotnet/roslyn-sdk/blob/d4e8061f34846fe992b2bcc933ab342c5447be71/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest%601.cs#L96-L105

**Comment by sharwell** [comment]
Why would a user need to assign `null` here?

**Comment by tom-englert** [comment]
Just to be able to continue using this when nullable is enabled:
```cs
public class AnalyzerTest<TAnalyzer> : CSharpAnalyzerTest<TAnalyzer, Verifier>
    where TAnalyzer : DiagnosticAnalyzer, new()
{
    public AnalyzerTest(string? source = null)
    {
        TestCode = source;
        ReferenceAssemblies = ReferenceAssemblies.Net.Net60;
    }
}
```
