### ISSUE TITLE
Syntax Visualizer Properties Type & Kind are not visible

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-sdk#111]
Moved from [link ](https://developercommunity.visualstudio.com/content/problem/211684/syntax-visualizer-properties-type-kind-are-not-vis.html)

The two properties Type and Kind above the Property Explorer Control in the Syntax Visualizer Tool Window are not visible when using the color theme "Dark".

**Comment by jinujoseph** [comment]
cc @sharwell

**Comment by sharwell** [comment]
This was fixed by #98
