### ISSUE TITLE
Add option to disable markup in tests

### ISSUE THREAD

**Issue by thinker227** [dotnet/roslyn-sdk#1114]
In the markup syntax used for tests, `$$` is a special reserved character. However, in C# 10+, `$$` can now occur in regular C# source code (raw string literals with one level of interpolation escaping). This makes it impossible to run tests containing `$$` naturally in the source code without overriding `AnalyzerTest<TVerifier>.RunImplAsync` to explicitly [*not*](https://github.com/dotnet/roslyn-sdk/blob/ca7df37e4c6b111eee5f9f29eeab3d40d23e1a67/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest%601.cs#L216C92-L216C92) call `WithProcessedMarkup`.

It would be useful if there either was an easily available option to disable markup entirely or there was some sort of markup escape character.

**Comment by Youssef1313** [comment]
@thinker227 This already exists.

https://github.com/dotnet/roslyn-sdk/blob/ca7df37e4c6b111eee5f9f29eeab3d40d23e1a67/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/MarkupOptions.cs#L15-L18

and

https://github.com/dotnet/roslyn-sdk/blob/ca7df37e4c6b111eee5f9f29eeab3d40d23e1a67/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/MarkupOptions.cs#L27-L33

**Comment by thinker227** [comment]
Oh, didn't know those existed.
