### ISSUE TITLE
Hang using `AnayzerTest`

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/roslyn-sdk#1119]
I got an hang using the `AnayzerTest` type.

<img width="971" alt="image" src="https://github.com/dotnet/roslyn-sdk/assets/7894084/32d50ff3-761f-4085-8ca8-68271e49cb7f">

The holding thread was stuck here

<img width="977" alt="image" src="https://github.com/dotnet/roslyn-sdk/assets/7894084/3ec3ebe4-b60a-48f8-b8e6-ab715e85b83e">

I wonder if a `.Result` is enough here.

cc: @sharwell  @Evangelink

**Comment by sharwell** [comment]
I'd need to see a heap dump to review this.
