### ISSUE TITLE
Naming: "Stand-alone Code Analysis Tool" should not be hyphenated

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-sdk#112]
@BillWagner commented on [Tue Mar 13 2018](https://github.com/dotnet/roslyn/issues/25445)

The templates delivered with the .NET Compiler Platform SDK includes one for a "Stand-Alone Code Analysis Tool".  Microsoft naming conventions follow the recommendations in the [American Heritage Dictionay](https://www.ahdictionary.com/word/search.html?q=standalone) where "Stand-alone" should not be hyphenated. It should be "Standalone".

**Comment by jpshrader** [comment]
I opened a PR for this, if it's still an issue (https://github.com/dotnet/roslyn-sdk/pull/510)
