### ISSUE TITLE
Roslyn analyzer tooltips not displaying escaped characters in IDE 

### ISSUE THREAD

**Issue by jezzsantos** [dotnet/roslyn-sdk#1124]
I have a custom Analyzer for a rule SAS010

You can see it working here in the Rider IDE.

![image](https://github.com/dotnet/roslyn-sdk/assets/3137590/2c4e209a-0611-4513-b190-a5870b4fd745)

The resource string being defined for it looks like this:
```xml
    <data name="SAS010MessageFormat" xml:space="preserve">
        <value>Method '{0}' should return either a Task&lt;T&gt; or T, where T is either an 'ApiEmptyResult', 'ApiResult&lt;TResource, TResponse&gt;' or 'ApiPostResult&lt;TResource, TResponse&gt;'</value>
    </data>
```

The problem is that the tooltip that pops up does not show the `<` and `>` signs in this text: `Task<T>`. (top of screenshot)
However, to be fair we do correctly see the escaped characters in the build warning (bottom of the screen shot).

Is this a Roslyn issue, or perhaps a Jetbrains Rider issue?

**Comment by sharwell** [comment]
I am not able to reproduce this in Visual Studio.
![image](https://github.com/dotnet/roslyn-sdk/assets/1408396/e9d9a336-b8fa-4960-ba96-431e251a8c77)

**Comment by jezzsantos** [comment]
Raised here in Rider: https://youtrack.jetbrains.com/issue/RIDER-100057/Escaped-Characters-in-Roslyn-Analyzer-diagnostic-messages-are-not-displayed-correctly-in-the-IDE.
