### ISSUE TITLE
remove reflection access to nested code actions.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn-sdk#1136]
API for this is now public.  See: https://github.com/dotnet/roslyn/pull/71327

**Comment by sharwell** [comment]
@CyrusNajmabadi roslyn-sdk continues to support old versions of roslyn. There are two viable options here:

1. A property with the name `NestedCodeActions` is preserved indefinitely
1. roslyn-sdk knows how to access the new property via light-up/reflection, and if not present falls back to using the old property via light-up/reflection

It is not expected that the SDK will ever have compile-time access to the new method.

**Comment by CyrusNajmabadi** [comment]
The latter works for me. I don't want to keep around old code for internal compat when there's a publicly available option. 

Once the SDK is updated, let's remove the bridge property.
