### ISSUE TITLE
new version of Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.XUnit on nuget

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [dotnet/roslyn-sdk#1159]
Hi,

could you please release latest version of Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.XUnit and its dependant packages - it is ultra beneficial for building independent source code analyzers.

Best regards

**Comment by sharwell** [comment]
This has now been resolved.
