### ISSUE TITLE
Analyzer / Source Generator testing framework doesn't work under Mono

### ISSUE THREAD

**Issue by YoshiRulz** [dotnet/roslyn-sdk#1171]
Regular MSTest works fine with Mono.

To reproduce:
1. Clone [repro project](https://github.com/YoshiRulz/roslyn-sdk-1171-repro) and checkout `07d7d3ba4^`
1. Run `dotnet test` from the `test` dir (uses .NET 8 Runtime)
1. Checkout `07d7d3ba4`
1. Run `dotnet test` again (uses Mono) and observe it now fails

Output:
```
Test run for /home/yoshi/Documents/roslyn-sdk-1171-repro/test/bin/Debug/net48/ReproAnalyzerTests.exe (.NETFramework,Version=v4.8)
Microsoft (R) Test Execution Command Line Tool Version 17.10.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed RunTest [11 s]
  Error Message:
   Test method ReproAnalyzerTests.RunTest threw exception: 
System.MethodAccessException: Method `Microsoft.CodeAnalysis.Testing.AnalyzerInfo+CustomAnalysisContext..ctor()' is inaccessible from method `CustomAnalysisContextImpl..ctor()'
  Stack Trace:
     at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_throw_method_access(intptr,intptr)
  at CustomAnalysisContextImpl..ctor () [0x00000] in <7dac18e8c9b545af8a708ace06c1f83f>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in <65a38edf81fe405bb4fb28e56b25f9d8>:0 


Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 11 s - ReproAnalyzerTests.exe (net48)
```

I'm taking the .NET SDK and Mono from the Nix expression which is checked-in to the repo—if you have Nix installed, you can run `nix-shell [--pure]` to get an identical environment. But I expect this affects all Linux systems.
```
$> dotnet --list-sdks
8.0.300 [/nix/store/8y83na7h81fw5kr1msmjc7rvx329djp0-dotnet-sdk-8.0.300/sdk]
$> dotnet --list-runtimes
Microsoft.AspNetCore.App 8.0.5 [/nix/store/8y83na7h81fw5kr1msmjc7rvx329djp0-dotnet-sdk-8.0.300/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.5 [/nix/store/8y83na7h81fw5kr1msmjc7rvx329djp0-dotnet-sdk-8.0.300/shared/Microsoft.NETCore.App]
$> mono --version
Mono JIT compiler version 6.12.0.182 (tarball Wed May 15 10:00:08 UTC 2024)
[...]
```

**Comment by sharwell** [comment]
Based on the stack trace, it appears Mono is not a supported runtime for this testing library and it would be particularly difficult to rewrite this code to make it work. We also don't have regression testing in place that would allow us to maintain the behavior even if we did find a way to make it work.

**Comment by YoshiRulz** [comment]
Can I ask that this be investigated further? Rejecting it based only on a stacktrace (which may be misleading) feels a bit dismissive to me.

**Comment by sharwell** [comment]
@YoshiRulz The stack trace suggests Mono does not support `IgnoresAccessChecksToAttribute`. Searches suggest this should have been fixed by https://github.com/dotnet/runtime/pull/48558, but we have no way to test this. If someone submitted a PR to this project to fix this, we would be looking for two things in particular:

1. General simplicity (a targeted fix to support Mono is more likely to be accepted if the fix is not complex)
2. Robustness (we have no way to run CI/regression tests for Mono, so the fix would need to be unlikely to break in the future _even without tests_)

**Comment by YoshiRulz** [comment]
Thank you for elaborating.
So do you believe that porting https://github.com/dotnet/runtime/commit/9102b07d846d812963420f022ce55ee1cbdb3b17 to standalone Mono would fix this for existing versions of Roslyn? With the transfer of ownership to WineHQ I can see that happening. I'm sure dotnet/runtime#37875 would also help.

**Comment by sharwell** [comment]
I'm not familiar enough with the Mono project to be able to answer that.
