### ISSUE TITLE
VSTS build is cancelled when a new commit is pushed to a branch

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-sdk#222]
After a build is started for a commit, VSTS should complete the build and post the build status to the GitHub commit even if a new commit is pushed to the branch. Currently, VSTS cancels the build and does not report a status at all, leaving the commit in a "pending" state.

**Comment by jmarolf** [comment]
@jaredpar I am not aware of a way to configure this behavior are you?

**Comment by jaredpar** [comment]
No. Let's follow up with the infra team about this.

**Comment by sharwell** [comment]
Resolving as external
