### ISSUE TITLE
Update nuspec for Microsoft.CodeAnalysis NuGet package

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-sdk#243]
Currently, this NuGet package has a development dependency on version 2.6.1 of Microsoft.CodeAnalysis.Analyzers NuGet package. That version of the analyzers package has a [known bug](https://github.com/dotnet/roslyn-analyzers/issues/1888), that causes an AD0001 diagnostic for large number of code bases. That bug is fixed in the latest version (2.6.3) of Microsoft.CodeAnalysis.Analyzers NuGet package, so we should updating the nuspec for Microsoft.CodeAnalysis to use version 2.6.3

**Comment by jmarolf** [comment]
`Microsoft.Codeanalysis` nuget is defined in dotnet/roslyn.  This issue should be moved there

**Comment by jinujoseph** [comment]
This issue was moved to dotnet/roslyn#32618
