### ISSUE TITLE
Testing Code Fixes does not allow alternate spacing or other formatting

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-sdk#33]
@KathleenDollard commented on [Sat Mar 14 2015](https://github.com/dotnet/roslyn/issues/1266)

When documents are compared after applying code fixes during testing, obviously, every character counts :)

The default of 4 spaces in the workspace used for creating the fixed documents is arbitrary, and results in significant challenges in creating test data when the developers machine uses a different spacing. 

I suggest modifying the VerifyCSharpTestFix and VerifyBasicTestFix methods to accept workspace options that can be added to the workspace prior to applying the new document. 

Allowing workspace formatting options here is preferable to allowing the indent space value because there are other formatting options someone may wish to apply. 

I've done this in my copy if you would like to see that code.

**Comment by sharwell** [comment]
Validating whitespace is intentional, as many code fixes depend on these details. Repositories are encouraged to use **.editorconfig** to avoid having per-machine differences in indentation while working on test suites.
