### ISSUE TITLE
Testing SDK: Generated call to "GetCSharpResultAt"/"GetBasicResultAt" doesn't contain message arguments

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn-sdk#341]
https://github.com/dotnet/roslyn-sdk/blob/fb6671f4c8a5400cc58586fd22e8c78936d3c02c/samples/CSharp/Analyzers/Analyzers.Test/Verifiers/DiagnosticVerifier.cs#L311

Here's an example test failure message:

```
  Message: Mismatch between number of diagnostics returned, expected "0" actual "1"
    
    Diagnostics:
    // Test0.cs(10,18): warning POD004: Parameter 'i' was never used
    GetCSharpResultAt(10, 18, ConstructorParameterNeverAssignedAnalyzer.POD004)
```

The generated call doesn't contain any message arguments, though. For my scenario the call should probably instead look like:
```cs
    GetCSharpResultAt(10, 18, ConstructorParameterNeverAssignedAnalyzer.POD004, "i")
```

It looks like users are meant to implement `DiagnosticResult GetCSharpResultAt(int line, int column, string id)` in their test classes. Can't the SDK itself provide this method? It seems like you just need:

```cs
public static DiagnosticResult GetCSharpResultAt(int line, int column, string id, params object[] args)
    => Diagnostic(id).WithArguments(args).WithLocation(line, column);
```

Alternatively, if the test failure message contained the `Diagnostic(id)...` call chain, that would be good too.

**Comment by sharwell** [comment]
📝 The generated message is a hold-over from the original testing framework. Nothing about it is correct (e.g. there is no method `GetCSharpResultAt`).
