### ISSUE TITLE
Update Workspaces dependencies

### ISSUE THREAD

**Issue by NextTurn** [dotnet/roslyn-sdk#396]
`Microsoft.CodeAnalysis.CSharp.Workspaces 1.0.1` and `Microsoft.CodeAnalysis.Workspaces.Common 1.0.1` do not support .NET Standard as the testing packages do.

**Comment by sharwell** [comment]
Can you clarify what the issue here is?

**Comment by NextTurn** [comment]
The `Microsoft.CodeAnalysis.*.Testing.*` packages support `netstandard2.0`, but their dependencies do not. Nuget generates warnings when restoring packages on a `netstandard2.0` project. The warnings can be resolved by adding a reference to the latest version of `Microsoft.CodeAnalysis.*.Workspaces` package.

> warning NU1701: Package 'Microsoft.CodeAnalysis.CSharp.Workspaces 1.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
warning NU1701: Package 'Microsoft.CodeAnalysis.Workspaces.Common 1.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
warning NU1701: Package 'Microsoft.Composition 1.0.27' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by sharwell** [comment]
Ah, this is by design. The testing library works with all versions of the workspaces library. Analyzer authors must choose the version they wish to test against.

**Comment by sharwell** [comment]
It wasn't by design for the 1.0.1 package to not work with .NET Standard, but it predated it so there was nothing available to properly support at the time.
