### ISSUE TITLE
Allow combination of markup syntax and Diagnostic(...)

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-sdk#411]
Currently, each test must choose between the use of markup syntax and a separately-specified `DiagnosticResult` instance for each reported diagnostic. The two approaches have different advantages:

* Markup syntax
    * Easier to see the span of a diagnostic in the context of surrounding code
    * Less work to maintain when lines are added to inputs and outputs
* Diagnostic(...) syntax
    * Allows for additional locations to be tested
    * Allows for diagnostic messages to be tested (and specifically arguments)
    * Allows severity to be tested explicitly

It would be nice to be able to specify the span using markup syntax, but still be able to provide other information via the `Diagnostic(...)` form.

**Comment by sharwell** [comment]
My current proposal is to use the syntax `{|#0:code|}`.

* `#0` references an explicit expected diagnostic with number `0` (the API for assigning a number to the corresponding explicit diagnostic is TBD)
* The numbers must be non-negative, but do not need to be sequential (a refactoring similar to dotnet/roslyn-analyzers#2588 can help with updating numbers)

**Comment by Evangelink** [comment]
It might be worth adding the markup ID inside of the expected diagnostic to avoid ordering  errors.

```csharp
await VerifyCS.VerifyAnalyzerAsync(@"
public class MyClass // expect another diag here
{
	public void {|#0:Foo()|} {} 
}
", 
	VerifyCS.Diagnostic().WithLocation(line: 2, column: 13).WithArgs("MyClass"),
	VerifyCS.Diagnostic(id: 0).WithArgs("Foo"));
```

**Comment by sharwell** [comment]
> It might be worth adding the markup ID inside of the expected diagnostic to avoid ordering errors.

My intent is this would be required. The number is a number, not an index.
