### ISSUE TITLE
Possible bug in new testing framework?

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn-sdk#418]
I am working on a codefix for https://github.com/taori/Amusoft.CodeAnalysis.Analyzers (CS1998) and in a unit test i am getting

`Assert.AreEqual failed. Expected:<1>. Actual:<0>. Context: Diagnostics of test state
Mismatch between number of diagnostics returned, expected "1" actual "0"` for my test in the branch features/cs1998-codefix for this code:

```cs
namespace ConsoleApplication1
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Threading.Tasks;
	using System.Diagnostics;
	using System.IO;

	public class TestClass
	{
		private string _workspaceFile;

		public async Task<Configuration[]> LoadStorageContentAsync()
		{
			var fileInfo = new FileInfo(_workspaceFile);
			if (!fileInfo.Exists)
			{
				Log.Error($"No configuration storage located at { fileInfo.FullName}.");
				return Array.Empty<Configuration>();
			}

			using (var stream = new StreamReader(new FileStream(fileInfo.FullName, FileMode.Open)))
			{
				try
				{
					var storage = new Storage();
					return storage.Configurations.ToArray();
				}
				catch (Exception e)
				{
					Log.Error(e);
					return Array.Empty<Configuration>();
				}
			}
		}

		public class Log
		{
			public static void Error(Exception p0)
			{
				throw new NotImplementedException();
			}

			public static void Error(string p0)
			{
				throw new NotImplementedException();
			}
		}

		public class Storage
		{
			public Configuration[] Configurations { get; set; }
		}
		public class Configuration
		{
			public Guid Id { get; set; }
			public string ConfigurationName { get; set; }
		}
	}
}
```

if i copy this code to the editor i'm getting a warning - but the Verifier does not seem to notice the warning?

@sharwell Could you verify please?

**Comment by taori** [comment]
test in question: [here](https://github.com/taori/Amusoft.CodeAnalysis.Analyzers/blob/ac229c1d8e84c5f7f357a5b18f8e7b1549993454/src/Amusoft.CodeAnalysis.Analyzers.Test/Tests/CS1998/FixByWrappingInTaskResultTests.cs#L158)

**Comment by sharwell** [comment]
The default behavior of the test framework is to ignore compiler warnings, but include compiler errors. You can override this behavior to ensure CS1998 is included.

```
await new VerifyCS.Test
{
  CompilerDiagnostics = CompilerDiagnostics.Errors | CompilerDiagnostics.Warnings,
  TestState = { Sources = { test } },
  FixedState = { Sources = { fixtest } },
}.RunAsync();

**Comment by sharwell** [comment]
I filed #419 for a specific improvement we can make in this space, which would allow the use of the simpler syntax while continuing to warnings unrelated to your scenario.

**Comment by taori** [comment]
Awesome! Thank you.
