### ISSUE TITLE
src/VisualStudio.Roslyn.SDK/Roslyn.SDK/obj/ is not excluded

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-sdk#430]
Clone the repo, call `restore.cmd`, `build.cmd`. Now you have one folder marked as `untracked`.

**Comment by jmarolf** [comment]
1. `build.cmd` does a restore automatically so the restore step shouldn't be needed
2. This does not reproduce on my windows machines. 

Can you run `git clean -xdf` and `Build.cmd` to confirm this is still happening on a clean enlistment?

**Comment by Evangelink** [comment]
Sure I'll try tomorrow but this was my first clone of the project so it was 100% fresh :)

**Comment by sharwell** [comment]
This is caused by https://github.com/dotnet/arcade/issues/2377
