### ISSUE TITLE
Visual Studio Project Template: "Analyzer with Code Fix": Verifier does not properly account for multiple source files

### ISSUE THREAD

**Issue by JakenVeina** [dotnet/roslyn-sdk#437]
The "Analyzer with Code Fix" Project Template includes quite a bit of boilerplate code for executing tests against user-implemented `DiagnosticAnalyzer` and `CodeFixProvider` classes. This includes code to compare a list of compiler-generated `Diagnostic` objects against a user-specified list of expected `DiagnosticResult` objects (as seen [here](https://github.com/dotnet/roslyn-sdk/blob/06807050c1db8f3c00d6f1392ef08251fe8b47af/src/VisualStudio.Roslyn.SDK/Roslyn.SDK/ProjectTemplates/CSharp/Diagnostic/Test/DiagnosticVerifier.cs#L119)). The template also supports specifying multiple source files for analysis (as seen [here](https://github.com/dotnet/roslyn-sdk/blob/06807050c1db8f3c00d6f1392ef08251fe8b47af/src/VisualStudio.Roslyn.SDK/Roslyn.SDK/ProjectTemplates/CSharp/Diagnostic/Test/DiagnosticVerifier.cs#L75)). However, the comparison algorithm relies on the two lists being properly sorted, and the method used to sort `Diagnostic` objects (as seen [here](https://github.com/dotnet/roslyn-sdk/blob/06807050c1db8f3c00d6f1392ef08251fe8b47af/src/VisualStudio.Roslyn.SDK/Roslyn.SDK/ProjectTemplates/CSharp/Diagnostic/Test/DiagnosticVerifier.Helper.cs#L93)) does not account for multiple source files being present. It simply sorts by `SourceSpan.Start`.

Proposed fix is in #436.

**Comment by jmarolf** [comment]
closed in https://github.com/dotnet/roslyn-sdk/pull/436
