### ISSUE TITLE
Using additional NuGet packages with 'Analyzer with Code Fix (.NET Standard)' and other issues

### ISSUE THREAD

**Issue by Glaeqen** [dotnet/roslyn-sdk#493]
**Steps to Reproduce**:

1. VS 2019 + VSIX Development SDK installed
2. Create project with template 'Analyzer with Code Fix (.NET Standard)'
3. Change `TargetFramework` in analyzer project to
```xml
<TargetFramework>netstandard2.0</TargetFramework>
```
4. Add a package to analyzer project (without .VSIX and .Test) (I used LibGit2Sharp in version 0.26.2)
5. Create a sample code using a dependency:
```csharp
public override void Initialize(AnalysisContext context)
{
    // TODO: Consider registering other actions that act on syntax instead of or in addition to symbols
    // See https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Analyzer%20Actions%20Semantics.md for more information
    // context.RegisterSymbolAction(AnalyzeSymbol, SymbolKind.NamedType);
    context.RegisterSyntaxTreeAction(analysisContext =>
    {
        AnalyzeSyntaxTree(analysisContext);
    });
}

private void AnalyzeSyntaxTree(SyntaxTreeAnalysisContext analysisContext)
{
    var repository = new Repository(); // Class from Lib2GitSharp
}
```
Important: Lambda calls another function using a resource from dependency. In case of
```csharp
context.RegisterSyntaxTreeAction(AnalyzeSyntaxTree);
```
or
```csharp
context.RegisterSyntaxTreeAction(analysisContext =>
    var repository = new Repository();
}
```
exception goes unnoticed and just nothing happens - which was very annoying to debug.

**Expected Behavior**:
Everything works and classes from NuGet package are accessible just fine.

**Actual Behavior**:
Exception is thrown
```
System.IO.FileNotFoundException: 'Could not load file or assembly 'LibGit2Sharp, Version=0.26.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333' or one of its dependencies. The system cannot find the file specified.'
```
![image](https://user-images.githubusercontent.com/20447270/76995774-a8e37300-6950-11ea-83b0-5db3d4d120a6.png)

Unfortunately I'm a newbie when it comes to a build system and I'm not sure how should I force it to copy proper DLLs to VSIX extension package or to NuGet package. @mrblindy from dotnet/roslyn#39682 had similar issue but only in case of NuGet package. I cannot even make it working in debug mode.
Thanks for help.

BTW:
I'm not sure why in `.Test` project in `Helpers/DiagnosticVerifier.Helper.cs` there's an error that `CreateReferenceFromFile` symbol cannot be resolved. Should I implement something or is this an issue with a template itself?
![image](https://user-images.githubusercontent.com/20447270/76996562-03c99a00-6952-11ea-8329-182112b77554.png)

**Comment by drewburlingame** [comment]
in case you found this page like I did because `CreateReferenceFromFile` is failing, change the code to `MetadataReference.CreateFromFile` and it will compile and run

**Comment by Glaeqen** [comment]
> 
> 
> in case you found this page like I did because `CreateReferenceFromFile` is failing, change the code to `MetadataReference.CreateFromFile` and it will compile and run

Well.. thanks for your response. Unfortunately, that one was the smallest of issues I'm struggling here with :/

**Comment by Glaeqen** [comment]
Eh, I'd love to have someone to take a look at this issue. I believe it is trivial to solve for someone familiar with msbuild.

**Comment by Glaeqen** [comment]
Is there anyone who could guide me into the right direction? What should I do to solve this issue?

**Comment by Glaeqen** [comment]
@sharwell ?

**Comment by sharwell** [comment]
> ... exception goes unnoticed and just nothing happens ...

> I have the same issue with the template where CreateReferenceFromFile cannot be found.

Both of these issues have been fixed for 16.7.

> Add a package to analyzer project ...

This is not (yet) a supported scenario for analyzer packages. There are some ways to make it work "accidentally", but you will _definitely_ be in a work-on-my-machine position, i.e. if you distribute the package publicly then it will work for some users and fail for other users, and the only real way to fix it is removing the dependency.

**Comment by Glaeqen** [comment]
@sharwell Well, it's a shame that it is currently impossible. Maybe I'm blind but I didn't find any disclaimer regarding this pretty limiting constraint :/ Either way, thank you for your response.

**Comment by sharwell** [comment]
@Glaeqen It's not a situation we wanted to be in or _intentionally_ created, but fell out of some of the implementation details. There are a hand full of related scenarios we definitely want to make work consistently in the future, so hopefully this is just a point-in-time issue.

**Comment by Glaeqen** [comment]
@sharwell Sorry, I didn't mean to sound harsh. I just wanted to say that it would very valuable to have such an important information easily available upfront eg. in README. Good luck in further development! :)
