### ISSUE TITLE
Syntax Visualizer shows SyntaxNodes but no Symbols

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn-sdk#504]
In Visual Studio 2019 and Visual Studio 2019 Preview the Syntax Visualizer shows only the type and kind name of a corresponding Symbol - but the grid is empty.
This worked in Visual Studio 2017.

![grafik](https://user-images.githubusercontent.com/26689688/78899171-483de680-7a75-11ea-8a22-9684fca1a318.png)

**Comment by bernd5** [comment]
Is the code in this repository for VS2019 or just VS2017?

**Comment by SENya1990** [comment]
I have the same problem - it works for VS 2017 but not for VS 2019

**Comment by SENya1990** [comment]
It seems I created a duplicate issue:
https://github.com/dotnet/roslyn-sdk/issues/546

**Comment by bernd5** [comment]
The grid seems to be generated via Reflection.
Perhaps there is some Exception while getting the data. The code in this repository looks fine (just a simple assignment) - but what is wrong?
How to debug it?

**Comment by bernd5** [comment]
Any news on this issue? I can work a bit with VS2017 but it's version does not support for example nullable reference types...
Please fix it or provide us some info that we can solve it...

**Comment by jmarolf** [comment]
I'll take a look this week

**Comment by bernd5** [comment]
Any news on this? Can we help you somehow?

**Comment by bernd5** [comment]
really great :-)

**Comment by bernd5** [comment]
Do you have any news on this? We work a lot with roslyn and need the visualizer to use it effectively.

**Comment by jzielnik** [comment]
Has this fix been released? I have similar issue but due fact that .NET 5 is not supported in VS2017 I cannot use it for these projects.

**Comment by bernd5** [comment]
Yes, it has been fixed. But I'm not sure where/when/how it is published.

**Comment by bernd5** [comment]
The issue was, that all symbols are implemented explictitly - and the View worked via reflection which searched for public properties.
