### ISSUE TITLE
File New Project Analyzer does not build

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/roslyn-sdk#514]
#### Repro steps

1. File -> New Project
2. Choose the **Analyzer with Code Fix (.NET Standard)** template

#### Expected behavior

1. Using the Vsix project as the startup project will start a new Visual Studio instance with the UPPERCASE analyzer example loaded.

#### Actual behavior

1. NuGet restore does not work due to ambiguous project names. This blocks debugging.
2. Unit test project does not compile.

**Comment by jinujoseph** [comment]
cc @jmarolf

**Comment by sharwell** [comment]
@KSchlobohm We've recently made substantial changes to the analyzer templates. Can you clarify which version of Visual Studio you used to create the analyzer project?

**Comment by KSchlobohm** [comment]
Visual Studio 2019 Version 16.6.0 Preview 4.0

**Comment by poke** [comment]
This also applies to both the release version 16.6.0 and also version 16.7.0 Preview 1.0.

As for the error with the test project, it has references to the following packages:

```xml
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing.MSTest" Version="1.0.1-beta1.*" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.MSTest" Version="1.0.1-beta1.*" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeRefactoring.Testing.MSTest" Version="1.0.1-beta1.*" />
```

But neither of these packages are published on NuGet. I was able to fix the references by adding the following to restore them from the preview feed:

```xml
<PropertyGroup>
  <RestoreAdditionalProjectSources>https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json;$(RestoreAdditionalProjectSources)</RestoreAdditionalProjectSources>
</PropertyGroup>
```

But then I also had to fix the test by replacing the `Verify`:

```diff
-using Verify = Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.MSTest.CodeFixVerifier<
+using Verify = Microsoft.CodeAnalysis.CSharp.Testing.MSTest.CodeFixVerifier<
     AnalyzerTest.AnalyzerTestAnalyzer,
     AnalyzerTest.AnalyzerTestCodeFixProvider>;

// …

-            await Verify.VerifyCSharpDiagnosticsAsync(test);
+            await Verify.VerifyAnalyzerAsync(test);

// …

-            await Verify.VerifyCSharpFixAsync(test, expected, fixtest);
+            await Verify.VerifyCodeFixAsync(test, expected, fixtest);
```

This fixed the test project.

As for the _“Ambiguous project name 'Analyzer1'”_ error, I was able to fix that by changing the assembly name of the Vsix project:

```diff
 <PropertyGroup>
   <TargetFramework>net472</TargetFramework>
   <RootNamespace>Analyzer1.Vsix</RootNamespace>
-  <AssemblyName>Analyzer1</AssemblyName>
+  <AssemblyName>Analyzer1Vsix</AssemblyName>
 </PropertyGroup>
```


But now when I’m building, I got this:

```
C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1005: Assets file 'C:\…\Analyzer1\Analyzer1\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.5.2'. Ensure that restore has run and that you have included 'net452' in the TargetFrameworks for your project.
```

There is only one reference to .NET 4.5.2, so I changed that to match the target framework of the analyzer project:

```diff
 <ItemGroup>
   <!-- https://github.com/dotnet/sdk/issues/433 -->
-   <ProjectReference Update="@(ProjectReference)" AdditionalProperties="TargetFramework=net452" />
+   <ProjectReference Update="@(ProjectReference)" AdditionalProperties="TargetFramework=netstandard2.0" />

   <!-- https://github.com/Microsoft/extendvs/issues/57 -->
   <ProjectReference Update="@(ProjectReference)" Name="%(Filename)" />
 </ItemGroup>
```

With these changes, I was able to properly compile and debug the analyzer. Hope this helps anyone else struggling with this!

**Comment by sharwell** [comment]
@dotnet/project-system do you know of any way to test project templates in CI?

**Comment by KeithLRobertson** [comment]
Thank you for the fix steps, @poke !

I lost hours on this before finding this issue. I second @sharwell  's idea to make testing the templates part of the CI pipeline.

**Comment by sharwell** [comment]
@KeithLRobertson So far I'm still not aware of a great way to test the templates. However, I found a _possible_ way to test the templates in #532 (the tests can be run manually but currently don't run in CI).

**Comment by AignerGames** [comment]
I think I have a similar problem with the "Code Refactoring (.NET Standard)" template using Microsoft Visual Studio Community 2019
Version 16.6.0

The template creates 2 projects:
- MyProjectName (actual code for the refactoring)
- MyProjectName.Vsix (additional project to build the vsix?)

And the following error:
NuGet packages: Ambiguous project name 

The problem is that both created projects have the same assembly name "MyProjectName".
Project properties -> Application -> Assembly name 

As a workaround I changed the assembly name of the .Vsix project from "MyProjectName" to "MyProjectName.Vsix". 

I don't know if this has any other side effects but the nuget error is gone and everything else seems to work too. Would be nice if the official template could be adjusted.

**Comment by stevenbrix** [comment]
@sharwell which version of VS are the new templates in?

**Comment by sharwell** [comment]
They should be in the 16.7 release.

**Comment by MCCshreyas** [comment]
@sharwell Is there any workaround yet without doing it manually? Updated template? Anything like that ?

**Comment by sharwell** [comment]
@MCCshreyas not yet. The template updates are coming in 16.7.

**Comment by paul1956** [comment]
@sharwell  The same problem still exists with VB Analyzers

**Comment by sharwell** [comment]
@paul1956 I fixed both the C# and the VB templates at the same time, so they'll eventually get updated in the distribution for 16.7.

**Comment by nenadvicentic** [comment]
@sharwell 

I have tried using "Analyzer with Code Fix (.NET Standard)" template from latest preview of Visual Studio 16.7.0 Preview 4.0 and the new project dialog fails. Clicking on `Create` button triggers ModalDialogBox with error:

> The path is not of a legal form.

Empty folder gets created on the disk, but without any project files.

**Comment by kofifus** [comment]
@nenadvicentic did you find a solution ?

**Comment by paul1956** [comment]
I reported this via Feedback yesterday, it reappeared with Preview 6. Workaround is don't use preview. But then the Analyzer doesn't build.

**Comment by nenadvicentic** [comment]
@paul1956 @kofifus That was my solution as well, not to use Preview version at all.

Still, there is a problem that even stable version of VS they use outdated/never-officially-published Nuget packages for testing of those components.

At the end I've built stand-alone console application to do the analysis/refactoring, which is not idea... Hopefully MS guys provide stable way forward for developing analyzers and code fixes for Visual Studio. Current situation is pretty bad and it's shame, because compiler itself is fully capable.

**Comment by sharwell** [comment]
@paul1956 The workaround is to use the preview version with the following sequence:

1. Create an **Empty Solution** from template
1. Add a project to the solution using the Analyzer and Code Fix template

**Comment by paul1956** [comment]
Thanks, is there a reason this is closed when in fact it does not work?

**Comment by sharwell** [comment]
The issue is assigned to an internal team. The templates were working fine in earlier 16.7 previews, prior to an unrelated product regression.

**Comment by sharwell** [comment]
Also note that this bug is marked fixed because the original issue https://github.com/dotnet/roslyn-sdk/issues/514#issue-603398634 is fixed. The unrelated issue was just a follow-up comment in https://github.com/dotnet/roslyn-sdk/issues/514#issuecomment-658680915.

**Comment by jmarolf** [comment]
@paul1956 The feedback ticked you filed [here](https://developercommunity.visualstudio.com/content/problem/1133261/cant-create-new-vb-vsix-project-with-codefix.html) is assigned to the extensibility team and we've pinged them. I will consider that the canonical place to track the "This path is not of a legal form" error. I will see if I can help the extensibility team figure out what was regressed.

**Comment by kofifus** [comment]
@sharwell I tried your suggestion above about creating a blank solution and adding the project from template, while creating the project I get:

![image](https://user-images.githubusercontent.com/3926071/89479712-d08b8880-d7d6-11ea-8fb6-80a626b50426.png)

Any help please ?

**Comment by paul1956** [comment]
@sharwell workaround worked for VB but the project has a hard reference to System.Collections.Immutable 1.2.5 and doesn't run with 1.7.0 this is probably a separate issue but not sure where to enter it, Roslyn, .Net Core, somewhere else?

**Comment by kofifus** [comment]
update -> all I had to do was remove all the visual basic items from the `Verifiers` folder and I managed to build and run fine

**Comment by nenadvicentic** [comment]
Another update - **VS19 16.7 (final)** does not fix the error **The path is not of a legal form**.

![image](https://user-images.githubusercontent.com/4405210/89506668-c3b56780-d7cb-11ea-8bb2-0388509ed59e.png)

**Comment by sharwell** [comment]
> Delete all Visual Basic items from the Verifiers folder

@kofifus For me, it is not necessary to do this step. Can you open a new issue for this?

> Another update - VS19 16.7 (final) does not fix the error The path is not of a legal form. VS19 16.8-preview1 also has the error.

@nenadvicentic This is a project system bug being investigated here:
https://developercommunity.visualstudio.com/content/problem/1133261/cant-create-new-vb-vsix-project-with-codefix.html

> ... has a hard reference to System.Collections.Immutable 1.2.5 and doesn't run with 1.7.0 ...

Can you open a new issue for this? It sounds unrelated to the other issues here.

**Comment by kofifus** [comment]
Hi are there any news about this ? is there any way to get a template that compiles with latest VS19 preview ?

**Comment by sharwell** [comment]
@kofifus The path error is fixed for 16.8 Preview 2. The workaround from https://github.com/dotnet/roslyn-sdk/issues/514#issuecomment-668781938 can be used in the meantime. For other problems, see https://github.com/dotnet/roslyn-sdk/issues/583#issuecomment-671531270 for the current status.

**Comment by kofifus** [comment]
Thanks @sharwell, until it is all released is there a way for you to provide a download of a solution with a project based on the C# codefix template that builds and runs all tests ? I am no successful in creating that

**Comment by sharwell** [comment]
@kofifus Can you create a new issue for the specific problem you are encountering?

**Comment by MrZarq** [comment]
> This also applies to both the release version 16.6.0 and also version 16.7.0 Preview 1.0.
> 
> As for the error with the test project, it has references to the following packages:
> 
> ```
> <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing.MSTest" Version="1.0.1-beta1.*" />
> <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.MSTest" Version="1.0.1-beta1.*" />
> <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeRefactoring.Testing.MSTest" Version="1.0.1-beta1.*" />
> ```
> 
> But neither of these packages are published on NuGet. I was able to fix the references by adding the following to restore them from the preview feed:
> 
> ```
> <PropertyGroup>
>   <RestoreAdditionalProjectSources>https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json;$(RestoreAdditionalProjectSources)</RestoreAdditionalProjectSources>
> </PropertyGroup>
> ```
>

For reference to future Googlers, this feed does not exist anymore. You now need to add the following feeds:
- https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
- https://pkgs.dev.azure.com/azure-public/vside/_packaging/vssdk/nuget/v3/index.json
- https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
 (it's likely only one of them is needed, but I didn't investigate further)
