### ISSUE TITLE
Breakpoints in the Analyzer not getting hit

### ISSUE THREAD

**Issue by pavanupb** [dotnet/roslyn-sdk#515]
Hi,
I am trying to debug my analyzer using the Vsix template in VS2019, but the breakpoints are not getting hit.
In the Vsix manifest file I have added my analyzer as an analyzer as well as MEF component.
Version Used
1. Analyzer - .Net Framework 4.7.2
2. Vsix - .Net Framework 4.7.2
3. Microsoft.CodeAnalysis.Analyzers 2.6.2

**Comment by sharwell** [comment]
@pavanupb We've recently made substantial changes to the analyzer templates. Can you clarify which version of Visual Studio you used to create the analyzer project?

**Comment by pavanupb** [comment]
@sharwell When I installed the latest template that gets shipped with VS 2019, the issue got resolved. Closing this issue.

**Comment by wajeehaKH** [comment]
I have updated versions in VS2019 but still my breakpoints are not going to hit.. Please help me

**Comment by sharwell** [comment]
@wajeehaKH Analyzers do not run in a single known process that allows debugging. The recommended approach is as follows:

1. For stepping through analyzers in the debugger, write unit tests using the analyzer test library (e.g. all the tests in dotnet/roslyn-analyzers). Visual Studio's Test Explorer allows individual tests to be run in a debugger.
2. For high-level validation that does not involve a debugger, the VSIX project may be used to launch Visual Studio with the analyzer enabled. This is meant as a general way to see how the analyzer behaves in a full project, but does not directly support debugging.

**Comment by wajeehaKH** [comment]
@SamHarwell I am debugging tests but still that part of code does not being
hit

**Comment by sharwell** [comment]
@wajeehaKH Can you file a new issue for that along with code to reproduce? If breakpoints are not hit while debugging tests, it means the code is not running. There are no known issues with the test library failing to execute analyzer code, so it's likely a bug exists in the analyzer or test itself.

**Comment by kswoll** [comment]
@sharwell I've found that adding `Debugger.Launch()` to my `Initialize` method works quite well to debug the analyzer in a real project.  Is there any reason that wouldn't be considered a reasonable (and possibly even recommended) approach?  Sometimes it's hard to write a test case when the analyzer has required nuget dependencies and symbol analysis, and this approach allows me to debug in realworld scenarios.

**Comment by sharwell** [comment]
> Is there any reason that wouldn't be considered a reasonable (and possibly even recommended) approach?

It's certainly possible to use this way, but it's not without downsides. You can force analyzers to run in-process (which supports debugging) by disabling this option in the experimental instance. Note that disabling this option will limit the size of solution that can be opened, and will make analysis slower.

![image](https://user-images.githubusercontent.com/1408396/107101852-7d1de580-67cd-11eb-8b84-18b7e82e43ff.png)

> Sometimes it's hard to write a test case when the analyzer has required nuget dependencies and symbol analysis

You can add NuGet dependencies via the `ReferenceAssemblies` property of tests. Here's an example:

https://github.com/dotnet/roslyn-sdk/blob/2bf7c285f3819862db0ba7030755bc81779fe705/tests/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing.UnitTests/CompilerErrorTests.cs#L349-L357

**Comment by kswoll** [comment]
Hi @sharwell, this was useful information, and I appreciate it, particularly the bit about the `ReferenceAssemblies`.  However, using the `Debugger.Launch` technique seems to work fine without disabling the `Use 64-bit process` setting.  That said, it's nice to know that that's an option for (I'm assuming?) debugging the analyzer without having to call `Debugger.Launch`.

**Comment by realvizu** [comment]
Just to help people who was wondering why turning off the "Use 64-bit process for code analysis" switch does not help: you might have overlooked (like me) that you have to make this change in **the experimental instance** of VS.

**Comment by FrankSzendzielarz** [comment]
For anyone else with this issue I managed to get breakpoints working again by downgrading the Analyzer's references to Microsoft.CodeAnalysis.Analyzers and Microsoft.CodeAnalysis.CSharp to 2.9.8 and 3.3.1 respectively, along with the use 64 bit process option above .

**Comment by hainh** [comment]
Another way for this issue if anyone still interests is turning this option off from VS instance containing test project/solution spawned after you press F5. Then your analysis breakpoint should hit again.
I'm using VS Community 2022 17.3.1, Microsoft.CodeAnalysis.CSharp 4.1.0, Microsoft.CodeAnalysis.Workspaces.Common 4.1.0
![image](https://user-images.githubusercontent.com/2195141/186108684-f7052dd2-aeab-46dd-8f30-8ceb6331ad59.png)

**Comment by d1820** [comment]
> Another way for this issue if anyone still interests is turning this option off from VS instance containing test project/solution spawned after you press F5. Then your analysis breakpoint should hit again. I'm using VS Community 2022 17.3.1, Microsoft.CodeAnalysis.CSharp 4.1.0, Microsoft.CodeAnalysis.Workspaces.Common 4.1.0 ![image](https://user-images.githubusercontent.com/2195141/186108684-f7052dd2-aeab-46dd-8f30-8ceb6331ad59.png)

This has also affected my extension even being able to run (multiple bug reports). There is definitely a bug in these packages to allow them to work properly out of process. What i noticed happening is none of the analyzers load even though the extension is loaded. Even redoing my extension to the latest templates from VS2022 17.6.5 with latest Niuget packages still had no effect until i unchecked run in separate process.
