### ISSUE TITLE
BasicAnalyzers and CSharpAnalyzers are deploying to the wrong hive

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-sdk#52]
@davkean commented on [Sun Feb 21 2016](https://github.com/dotnet/roslyn/issues/8995)

![image](https://cloud.githubusercontent.com/assets/1103906/13205247/eabee914-d898-11e5-88ef-199f2af3a095.png)

This should be 14.0RoslynDev, not 14.0Roslyn.

---

@davkean commented on [Sun Feb 21 2016](https://github.com/dotnet/roslyn/issues/8995#issuecomment-186911748)

Also, why do they have @mavasani's user name as company?

---

@jmarolf commented on [Sun Feb 21 2016](https://github.com/dotnet/roslyn/issues/8995#issuecomment-186920606)

Thats the default info that the SDK generates when you create a new project.  We deploy to the `Roslyn` in the SDK and use your username.

---

@mavasani commented on [Sun Feb 21 2016](https://github.com/dotnet/roslyn/issues/8995#issuecomment-186927060)

Yes, just need to update it.

---

@diryboy commented on [Tue Feb 23 2016](https://github.com/dotnet/roslyn/issues/8995#issuecomment-187751208)

If users are writing analyzers themselves, things get deployed to the Roslyn suffix, isn't that samples are also expected to be deployed to the same suffix?

---

@davkean commented on [Tue Feb 23 2016](https://github.com/dotnet/roslyn/issues/8995#issuecomment-187762691)

Yeah, perhaps. Either way they should be deployed to "Roslyn" or all deployed to "RoslynDev" - not a mix.

**Comment by sharwell** [comment]
Deploying to Roslyn avoids conflicts with other analyzers being deployed experimental instances by builds of dotnet/roslyn and dotnet/roslyn-analyzers.
