### ISSUE TITLE
How to modify existing method with Source Generator?

### ISSUE THREAD

**Issue by ardacetinkaya** [dotnet/roslyn-sdk#528]
Currently I can create additional codes, but also want to add these additional codes to existing ones.

In _ISourceGenerator_ derived class, I add a new *.cs file with a static code in Execute() method.
I can access the sytanxnodes but can not modify the existing code due to immutable structure.

So how can I modify the existing one?

**Comment by jmarolf** [comment]
We made and explicit design choice to not allow you to modify existing code. Please [file an issue](https://github.com/dotnet/roslyn/issues/new) on roslyn if you would like this changed
