### ISSUE TITLE
Samples.sln is cannot locate Microsoft.CodeAnalysis dll

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-sdk#53]
@zanqi commented on [Wed Mar 16 2016](https://github.com/dotnet/roslyn/issues/9824)

**Version Used**: Code Pulled on Mar 16th, 2016

**Steps to Reproduce**:
1. Clone https://github.com/dotnet/roslyn
2. Run the "Developer Command Prompt for VS2015" from your start menu.
3. Navigate to the directory of your Git clone.
4. Run Restore.cmd in the command prompt to restore NuGet packages.
5. Run msbuild /v:m /m Roslyn.sln
6. Open src/Samples/Samples.sln

**Expected Behavior**:Samples.sln can be opened without reference warnings

**Actual Behavior**: Step 5 built fine, but when Samples.sln is opened, all references to Microsoft.CodeAnalysis have warnings stating the dll can not be located. If there's a step needed to install these dll, please provide it on [Samples and Walkthroughs](https://github.com/dotnet/roslyn/wiki/Samples-and-Walkthroughs)

**Comment by mainxx** [comment]
I also have this problem. I found it after examination.
The path **"C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.entityframeworkcore.analyzers\2.1.0\analyzers\dotnet\cs\Microsoft.EntityFrameworkCore.Analyzers.dll"** does not exist

"Microsoft. CodeAnalysis. DLL" actually exist in **"C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.entityframeworkcore.abstractions\2.1.0\lib\netstandard2.0"** path,

I want to know how to modify this path

**Comment by jmarolf** [comment]
@mainxx this bug relates to opening the code in this repo. You issue appears to be unrelated.  Can you post exact repro steps to reproduce your issue? Otherwise I would contact the owners of [Microsoft.EntityFrameworkCore.Analyzers](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Analyzers/)

**Comment by mainxx** [comment]
It didn't affect my project.
 I just wanted to know why I had this warning.

![2](https://user-images.githubusercontent.com/14832636/41528684-508a7be8-731d-11e8-93bc-4543b9838995.gif)

**Comment by sharwell** [comment]
Haven't heard about this being a problem in a long time.
