### ISSUE TITLE
NuGet reference in analyzer tests. DependencyBehavior.Lowest?

### ISSUE THREAD

**Issue by KatoStoelen** [dotnet/roslyn-sdk#550]
Hi,

I'm wondering if the problem I'm facing is related to this line of code:

https://github.com/dotnet/roslyn-sdk/blob/8647b801e8696dfc566bf18f2e7df34822ad3255/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs#L255

In my analyzer test, I have two `PackageIdentity`s added to the reference assemblies.

`ReferenceAssemblies = ReferenceAssemblies.NetCore.NetCoreApp31.AddPackages(...)`

One of the packages has a dependency on `Microsoft.Extensions.DependencyInjection.Abstractions` v3.0 and the other has a dependency on v3.1. When running the test, I get the following compilation error:

```
error CS1705: Assembly 'Package depending on v3.1' with identity 'Package depending on v3.1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.DependencyInjection.Abstractions' with identity 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

And looking at the `test-packages` temp directory, it does indeed seem like v3.0 is preferred over v3.1.

If the referenced line of code is the reason this happens and it is by design, what is the reasoning behind DependencyBehavior.Lowest?

Adding a `PackageIdentity` of `Microsoft.Extensions.DependencyInjection.Abstractions` v3.1 explicitly is a possible workaround. However, I did expect it to work without having to do so.

**Comment by jmarolf** [comment]
CC: @sharwell

**Comment by KatoStoelen** [comment]
Found some information about it in this blog post: https://martinbjorkstrom.com/posts/2018-09-19-revisiting-nuget-client-libraries#resolve-the-dependency-graph-from-the-list-of-available-packages

Without being able to understand why `Lowest` would be better than `Highest`.

I understand that there's alot of complexity in this area, and I would be fine with the workaround explained above.

**Comment by sharwell** [comment]
Ideally we want the behavior used by `dotnet restore`. Unfortunately it's nearly impossible to find information on how that works exactly :(

**Comment by KatoStoelen** [comment]
I see. I'm fine with closing this issue. Finding the ideal solution is probably more painful than having to add a few more package references to make the tests run.

Thanks for quick feedback!
