### ISSUE TITLE
Support for "local" NuGet.Config files in analyzer tests

### ISSUE THREAD

**Issue by KatoStoelen** [dotnet/roslyn-sdk#551]
The current implementation

https://github.com/dotnet/roslyn-sdk/blob/8647b801e8696dfc566bf18f2e7df34822ad3255/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs#L203

only loads machine and user wide NuGet configuration. In some scenarios you might want to keep the configuration local to the solution, to avoid cluttering the user/machine wide configuration (on build agents etc.).

Would it be possible to find a sensible value for the `root` parameter to enable configuration file search by traversal? Or would we then run into all sorts of issues with test frameworks running the tests in different working directories?

**Comment by sharwell** [comment]
It would not be desirable to use the same NuGet configuration as the analyzer project. It would be good to support other NuGet sources via a test API of some sort though (likely a property of the `ReferenceAssemblies` type).

**Comment by KatoStoelen** [comment]
Makes sense. APIs for adding/customizing NuGet sources would be great!
