### ISSUE TITLE
[Question] Connect a piece of code to its using statement

### ISSUE THREAD

**Issue by MCKRUZ** [dotnet/roslyn-sdk#589]
If this isn't the forum for this I apologize but I have tried everywhere else.  Is there anyway to connect a piece of code to its "using" statement using the Roslyn framework?

For example, given this piece of code:

```csharp
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Serilog;
using System.Collections.Generic;

namespace CodeAnalyzer.Service.CodeAnalysis.CSharp
{
	public static class CSharpCodeAnalyser
	{

		/// <summary>
		/// Retrieves all of the using statements from a code page
		/// </summary>
		/// <param name="codeDocument"></param>
		/// <param name="logger"></param>
		/// <returns></returns>
		public static List<string> IdentifyUsings(string codeDocument, ILogger logger)
		{
			var usingList = new List<string>();

			try
			{
				SyntaxTree tree = CSharpSyntaxTree.ParseText(codeDocument);
				CompilationUnitSyntax root = tree.GetCompilationUnitRoot();
				foreach (var item in root.Usings)
				{
					usingList.Add(item.Name.ToString());
				}
			}
			catch (System.Exception ex)
			{
				logger.Error(ex, ex.Message);
				throw;
			}

			return usingList;
		}
	}
}
```

Could I know that "CSharpSyntaxTree" belongs to the "Microsoft.CodeAnalysis.CSharp" using?

**Comment by jmarolf** [comment]
@MCKRUZ can you go into detail about what problem you are trying to solve? I would have assumed that a symbol based approach here would be more expedient.

**Comment by MCKRUZ** [comment]
@jmarolf sure no problem.  The basic idea of what I'm trying to achieve is this:

I have an engine that analyzes commits to a Git Repo.  Through those commits I can assess which developers made changes to which files.  So in the example above I can say "Developer X added a line to the CSharpAnalyzer class "SyntaxTree tree = CSharpSyntaxTree.ParseText(codeDocument);:"

With this knowledge I want to be able to know which DLL's this code references.  In this case it references the using statement Microsoft.CodeAnalysis.CSharp namespace, which leads back to the assembly Microsoft.CodeAnalysis.CSharp.Workspaces.

This way I can know that a developer did work utilizing that Assembly and I can denote that so when I go to evaluate my developers work on the project I can assess what skills they picked up.

**Comment by jmarolf** [comment]
ok, so if I am understanding you, given text such as `using Serilog;` you want to be able to say that this assembly `Serilog.dll` is being used?

**Comment by MCKRUZ** [comment]
Close, given a piece of text like

Logger.logInformation(“test”


I want to link it to the “using serilog” that will then link me to serilog

**Comment by jmarolf** [comment]
The normal way I would approach this would be to call `SemanticModel.GetTypeInfo` which will give you a `TypeInfo` object. From there you can examine the TypeInfo.Symbol object and look at its `ContainingSymbol`.  That would typically be how I get its namespace. Looking at just the syntax tree there is no way to know what symbols map to which assemblies/symbols.

**Comment by MCKRUZ** [comment]
Can you provide an example?  Every time I use SemanticModel.GetTypeInfo I get back nothing.

**Comment by MCKRUZ** [comment]
I think I know why this isn't working.  I need to load in a workspace instead of a string correct?

**Comment by MCKRUZ** [comment]
So I figured out how to do this.

First I needed to build a workspace containing my entire solution. I did this through the Buildalyzer tool

        public static Tuple<AdhocWorkspace, IEnumerable<Project>> GetWorkspace(string solutionFilePath, ILogger logger)
    {
        Tuple<AdhocWorkspace, IEnumerable<Project>> results;
        var projectList = new List<Project>();
        AdhocWorkspace workspace = new AdhocWorkspace();


        try
        {
            AnalyzerManager manager = new AnalyzerManager(solutionFilePath);
            foreach (var project in manager.Projects)
            {
                projectList.Add(project.Value.AddToWorkspace(workspace));
            }
            results = new Tuple<AdhocWorkspace, IEnumerable<Project>>(workspace, projectList);
        }
        catch (Exception ex)
        {
            logger.Error(ex, ex.Message);
            throw;
        }
        return results;
    }
Once I had a workspace all I needed to do was the following:

var workspace = GetWorkspace(solutionName, _logger);


                foreach (var project in workspace.Item1.CurrentSolution.Projects)
                {
                    foreach (var document in project.Documents)
                    {
                        _logger.Information("");
                        _logger.Information(project.Name + "\t\t\t" + document.Name);
                        var semanticModel = await document.GetSemanticModelAsync();
                        var root = await document.GetSyntaxRootAsync();

                        foreach (var item in root.DescendantNodes())
                        {
                            var typeInfo = semanticModel.GetTypeInfo(item);
                            if (typeInfo.Type != null)
                            {
                                _logger.Information(String.Format("Node: {0}", item.ToString()));
                                _logger.Information(String.Format("Type:{0}", typeInfo.Type.Name.ToString()));
                                _logger.Information(String.Format("ContainingAssembly:{0}", typeInfo.Type.ContainingAssembly));
                                _logger.Information(String.Format("ContainingNamespace:{0}", typeInfo.Type.ContainingNamespace));
                            }

                        }

                        
                    }
                }
