### ISSUE TITLE
VB analyzer template needs code cleanup (polish)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-sdk#598]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1164009/latest-analyzer-template-project-has-several-issue.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
There are some minor issues in the template that should be cleaned up

* ~Missing .editorconfig~ (moved to #610)
* ~Missing AnalyzerReleases.( Un)shipped.md)~ (moved to #611)
* Missing ReadOnly (fixed by #609)
* ~Missing ConfigureGeneratedCodeAnalysis~ (moved to #603)
* Missing EnableConcurrentExecution (fixed by #609)

I would do a PR but which Repo are the default templates or where should they be reported if not Open Source, also reported in another Feedback is they don't work if NuGet packages are upgraded.

To reproduce, create new VB solution from "Analyzer With Code Fix (.Net Standard)" using Microsoft Visual Studio Community 2019 Preview
Version 16.8.0 Preview 2.0.

---
#### Feedback Bot on 8/26/2020, 11:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/28/2020, 09:38 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by paul1956** [comment]
"Rule" should be read only IDE0044 should also be changed as below
```
Private Shared Rule As New DiagnosticDescriptor(DiagnosticId, Title, MessageFormat, Category, DiagnosticSeverity.Warning, isEnabledByDefault:=True, description:=Description,helpLinkUri:=Nothing,                                                         Array.Empty(Of String))
```

**Comment by sharwell** [comment]
> "Rule" should also be changed to avoid allocation of empty array.

This is not necessary. The descriptor is a singleton field, and even the case of a per-call allocation in `SupportedDiagnostics` has not shown up as measurable (let alone observable) in profiling.

**Comment by paul1956** [comment]
Then why is VS complaining? I just prefer to have no Errors, Warnings or suggestions, maybe I am too OCD.

**Comment by sharwell** [comment]
> Then why is VS complaining?

VS should not be complaining about this. It sounds like a custom analyzer has been installed. What is the diagnostic ID?

**Comment by paul1956** [comment]
```
Message	CA1825	Avoid unnecessary zero-length array allocations.  Use Array.Empty(Of String)() instead.
```

**Comment by sharwell** [comment]
That's an analyzer false positive that was supposed to be fixed by https://github.com/dotnet/roslyn-analyzers/pull/905.

**Comment by paul1956** [comment]
@sharwell It still exists in Microsoft Visual Studio Community 2019 Preview
Version 16.8.0 Preview 2.1
