### ISSUE TITLE
Analyzer template not working for accounts with long user names

### ISSUE THREAD

**Issue by MichaRotstein** [dotnet/roslyn-sdk#601]
I just tried again to create C# analyzer codefix project with the new Version 16.8.0 Preview 2.0
I get:

![image](https://user-images.githubusercontent.com/65199232/91680247-f87bcb00-eb8d-11ea-8007-d2ba616a399f.png)

I have now been trying to simply create and build the c# analyzer template which should be trivial for over a month with no luck. Many issues have been opened and get closed without this resolved.

**Comment by sharwell** [comment]
I believe this is caused by the path being too long. Can you tell me the total number of characters appearing in the value for `%USERPROFILE%`? For every character we shorten the longest names, one additional character can appear in this path.

**Comment by MichaRotstein** [comment]
thanks @sharwell , how do I get this variable ?

**Comment by sharwell** [comment]
For me, the path is:

> C:\\Users\\sam\\AppData\\Local\\Microsoft\\VisualStudio\\16.0_80a394a5\\VTC\\45823ca21c203519dc399b38d579e61d\\~PC\\CSharpDiagnostic\\CSharp\\Extensibility\\1033\\CSharpDiagnostic.zip\\ProjectTemplates\\CSharp\\Diagnostic\\Test\\Verifiers\\CSRefactoringVerifier`1+Test.cs

This is 250 characters, so without special system configuration I would expect the template to work for a user with a username up to 13 characters. `Micha Rotstein` is 14 characters. ☹️ Removing one or more characters from the path to this template file should resolve the issue for you.

**Comment by MichaRotstein** [comment]
OK thanks , how do I do that ? (without changing my username)

**Comment by sharwell** [comment]
A proper fix requires modification to the templates themselves, or fixing the IDE to stop producing paths this long in the template cache. In the meantime, the three ways to fix this would be:

1. Generate the project on a machine/account which is shorter, after which time it will work everywhere.
2. Manually create the missing file(s) based on the expected content
3. Delete **CSharpRefactoringVerifier`1.cs** and the VB equivalent, which means you can't test code refactorings but you might not need this anyway

**Comment by MichaRotstein** [comment]
Sorry but I can't see how any of these solutions will work for me, I have never had these kind of issues with any other template.

Is there a way to provide us with a project based on the template without any modifications that builds ?

**Comment by sharwell** [comment]
Here are the templates for the two files that failed to generate:

https://github.com/dotnet/roslyn-sdk/blob/master/src/VisualStudio.Roslyn.SDK/Roslyn.SDK/ProjectTemplates/CSharp/Diagnostic/Test/Verifiers/CSRefactoringVerifier%601+Test.cs
https://github.com/dotnet/roslyn-sdk/blob/master/src/VisualStudio.Roslyn.SDK/Roslyn.SDK/ProjectTemplates/CSharp/Diagnostic/Test/Verifiers/VBRefactoringVerifier%601%2BTest.cs

You'll need to make the following changes:

1. Rename the files to **CSharpRefactoringVerifier\`1+Test.cs** and **VisualBasicRefactoringVerifier\`1+Test.cs**, respectively
2. Change the namespace `$safeprojectname$` listed in the file to match the namespace that appears in the file  **CSharpRefactoringVerifier\`1.cs** that did generate successfully
