### ISSUE TITLE
Source Generator with .Net Core WPF application

### ISSUE THREAD

**Issue by tombrothers** [dotnet/roslyn-sdk#635]
How do you configure a .Net Core WPF application to work with source generators?

I'm trying to use the SourceGeneratorSamples AutoNotifyGenerator in a .Net Core WPF application but there seems to be an issue with the way the WPF application is compiled.  It looks like the WPF build process is creating a temporary project for compilation which I guess doesn't have access to the SourceGeneratorSamples project.

**Comment by jmarolf** [comment]
@chsienki what is the WPF issue that is tracking this?

**Comment by tombrothers** [comment]
@jmarolf  - I suspect that this is the [issue](https://github.com/dotnet/wpf/issues/3404).

Also, I found [this](https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#wpf-projects-unable-to-generate-grpc-c-assets-from-proto-files) work around for now.
