### ISSUE TITLE
Markup doesn't like spans in the middle of escape characters

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn-sdk#637]
Given:

```cs
//                       11     1   1
//             012345678901     2   3
string code = "class C { }\r{|b:\n|}";`
```

The markup produces a span at 12..14, and an output text of `class C { }\r\r\n`.

The span should be 12..13 and the output should only have one `\r`

**Comment by sharwell** [comment]
I was not able to reproduce this. A regression test is added in #683.
