### ISSUE TITLE
How to install a dev build of roslyn-sdk in VS2019

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn-sdk#638]
Today was Visual Studio 2019 Preview 16.8.4 released and I thought that we might see the current version of the roslyn-sdk in visual studio.

But I see just a "dummy" version (with a color picker) which I created to see if something changed / the edited code was loaded by Visual Studio.
I don't know how I installed it (I just wanted to debug it....).

I did already  "uninstall/install" of roslyn-sdk via vs-installer, "reset all settings" and a "repair installation" of my visual studio. But my debug-version of the roslyn sdk seems to be still installed. So my question is: how can I install/uninstall roslyn-sdk in Visual studio correctly?

**Comment by bernd5** [comment]
I checked the code again. There was someone else who added a color picker to the syntax-visualizer, too....

When is the current roslyn SDK released / available to use in the preview version?

**Comment by jmarolf** [comment]
> When is the current roslyn SDK released / available to use in the preview version?

the version in master will be available in 16.9 preview 1

**Comment by bernd5** [comment]
Thanks, is it possible to install right now?

**Comment by bernd5** [comment]
Now it works for me. I replaced simply all dlls in the Common7\IDE\Extensions\{something} folder with those generated by the roslyn build-script.
