### ISSUE TITLE
Intellisense reporting error for source generated type, but runs fine

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/roslyn-sdk#660]
The intellisense keeps reporting an error that the source generated type doesn't exist, but the type is found in the assembly and and the error doesn't block the build anyway.

Repro:
1. Clone https://github.com/davidwengier/SourceGeneratorTemplate
1. Open VS2019 16.8.1
2. Run ConsoleApp
3. Note that it runs fine and `Foo` is listed as a type in the assembly
4. Open `Program.cs` in ConsoleApp
5. Add `var foo = new Foo();`

EXPECTED: Type is recognized.

ACTUAL: Get compiler error

> The type or namespace name 'Foo' could not be found (are you missing a using directive or an assembly reference?)

![image](https://user-images.githubusercontent.com/1784452/100014239-baacce00-2d9b-11eb-9a36-371e563c376e.png)

7. Run ConsoleApp
8. Note that it runs fine even with the error

**Comment by jmarolf** [comment]
@chsienki should this be in this repo or moved to roslyn?

**Comment by ugumba** [comment]
Seconded.  Without Intellisense, generated code is almost impossible to consume - especially as it is not even put anywhere on disk (that I could find).

**Comment by chsienki** [comment]
I'm pretty sure this is another case of https://github.com/dotnet/roslyn/issues/48083

I'll close this as a dupe, but feel free to add onto the referenced bug.
