### ISSUE TITLE
Roslyn nuget packages for Azure DevOps feeds

### ISSUE THREAD

**Issue by javierdlg** [dotnet/roslyn-sdk#665]
Are there any plans to move away from MyGet for nuget packages? These are not compatible with DevOps package feeds and can't be used for DevOps projects.

**Comment by JoeRobich** [comment]
Hi @javierdlg , Currently rolling builds are published to Azure Artifacts (See https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-tools&package=Microsoft.CodeAnalysis.Analyzer.Testing&protocolType=NuGet&version=1.0.1-beta1.20605.1).
