### ISSUE TITLE
Improve exception message when VerifyCodeFixAsync(code, code) fails

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-sdk#697]
See https://github.com/dotnet/roslyn-analyzers/pull/4700/files#r558434203

**Comment by sharwell** [comment]
What was the old exception message? Do you have a suggestion for specific improvement?

**Comment by Youssef1313** [comment]
@sharwell Message:

```
    Microsoft.CodeAnalysis.Testing.Verifiers.EqualWithMessageException : Context: Iterative code fix application
    Expected '0' iterations but found '1' iterations.

```

The scenario was: A codefix is offered with no changes, i.e:

![image](https://user-images.githubusercontent.com/31348972/123142298-901e1300-d459-11eb-89a0-fae9de799672.png)


It didn't make sense to me at that time. While now I think it makes sense, it may be confusing to people new to writing analyzers.
A more clear message would be something similar to "Expected no codefixes, found a code fix that doesn't change code".
