### ISSUE TITLE
ReferenceAssemblies.ResolveAsync does not return assemblies from nuget ref folder

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-sdk#699]
Given such code as:

```cs
ReferenceAssemblies references = ReferenceAssemblies.NetStandard.NetStandard20
    .AddPackages(ImmutableArray.Create(
        new PackageIdentity("System.Memory", "4.5.4"),
        new PackageIdentity("Microsoft.Windows.SDK.Contracts", "10.0.19041.1")));
ImmutableArray<MetadataReference> metadataReferences = await references.ResolveAsync(LanguageNames.CSharp, default);
```

The resulting metadata references contains all the netstandard2.0 assemblies as well as System.Memory, but it does not include any of the many winmd's from the `Microsoft.Windows.SDK.Contracts` package, all of which appear under the `ref\netstandard2.0` folder.

**Comment by sharwell** [comment]
The **ref** folder was already supported, but **.winmd** (and **.exe**) assembly extensions were not.

**Comment by AArnott** [comment]
Thanks for fixing!

**Comment by sharwell** [comment]
Feel free to reach out directly in the future if you need something that appears to be overlooked

**Comment by AArnott** [comment]
@sharwell, this isn't fixed in what appears to be the latest version: 
```xml
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.XUnit" Version="1.1.2-beta1.23163.2" />
```

Is the fix in a later version that I don't see?
