### ISSUE TITLE
How to retrieve project's default namespace within Source Generator?

### ISSUE THREAD

**Issue by xperiandri** [dotnet/roslyn-sdk#704]
As I want to generate some code within some project I want to use the default namespace of that project in generated code.
But how to retrieve it???

**Comment by jmarolf** [comment]
see [Consume MSBuild properties and metadata](https://github.com/dotnet/roslyn/blob/master/docs/features/source-generators.cookbook.md#consume-msbuild-properties-and-metadata). You want to consume the `RootNamespace` property.

**Comment by xperiandri** [comment]
Yahoo! Works!
https://github.com/xperiandri/JsonSchemaToSource
@jmarolf, thanks!
