### ISSUE TITLE
Using netstandard2.1 in Source Generators

### ISSUE THREAD

**Issue by aelij** [dotnet/roslyn-sdk#705]
When I change my generator library to `netstandard2.1` I get an error saying it can't locate `netstandard.dll`:

> CSC : warning CS8032: An instance of analyzer MyGenerator cannot be created from bin\Debug\netstandard2.1\MyGenerator.dll : Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

Is there a way to make it work? Or is it limited by the fact that generators run in the VS MSBuild that targets `net48`?

I also tried multi-targeting to `net48;netcoreapp3.1` and got a similar error about `System.Runtime`.

**Comment by jmarolf** [comment]
> I also tried multi-targeting to net48;netcoreapp3.1 and got a similar error about System.Runtime.

Even if you multi-target we do not have a mechanism to selectively tell MSBuild which assembly to load. As of right now this behavior is by-design. You will need to target netstandard2.0
