### ISSUE TITLE
Adding AdditionalFiles in test

### ISSUE THREAD

**Issue by kYann** [dotnet/roslyn-sdk#716]
Hello,

When using CSharpAnalyzerVerifier how can I add AdditionalFiles for my analyzer ?

Thanks,

Yann

**Comment by jmarolf** [comment]
I don't think this is supported right @sharwell?

**Comment by sharwell** [comment]
It's supported through the AdditionalFiles property.

**Comment by sharwell** [comment]
I can give a more complete answer when I'm back at a computer 🙂

**Comment by sharwell** [comment]
Here's a test with additional files:

https://github.com/dotnet/roslyn-sdk/blob/2bf7c285f3819862db0ba7030755bc81779fe705/tests/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing.UnitTests/AdditionalFilesTests.cs#L19-L34

Here's a test where an additional file is added by a code fix:

https://github.com/dotnet/roslyn-sdk/blob/2bf7c285f3819862db0ba7030755bc81779fe705/tests/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing.UnitTests/AdditionalFilesFixTests.cs#L23-L41

**Comment by kYann** [comment]
Thanks, it's working !
