### ISSUE TITLE
Issues building the default analyzer + codefix template

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-sdk#718]
See https://github.com/Youssef1313/YAnalyzers/pull/7

With the first commit, I'm adding a GH Action that tries to build the default template. It fails with:

```
Error: /home/runner/.dotnet/sdk/5.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1060: Error reading assets file: Error loading lock file '/home/runner/work/YAnalyzers/YAnalyzers/YAnalyzers/YAnalyzers.CodeFixes/obj/project.assets.json' : 'home/runner/work/YAnalyzers/YAnalyzers/YAnalyzers/YAnalyzers/YAnalyzers.csproj*/1.0.0' is not a valid version string. (Parameter 'value') [/home/runner/work/YAnalyzers/YAnalyzers/YAnalyzers/YAnalyzers.CodeFixes/YAnalyzers.CodeFixes.csproj]
```

The reason is the path separator being the same as the package version separator on Linux.

This is caused by the usage of `MSBuildProjectFullPath`  introduced with https://github.com/dotnet/roslyn-sdk/pull/532/commits/d4e965676a88fd0a236c7a2aeb5402dfe8b0c36d. I'm not sure what the proper fix is.

---

With the second commit where I switched to Windows, it fails with:

```
C:\Users\runneradmin\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VsSDK.targets(80,5): error MSB4062: The "CompareCommonBuildTaskVersion" task could not be loaded from the assembly C:\Users\runneradmin\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.dll. Could not load file or assembly 'System.IO.Packaging, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\a\YAnalyzers\YAnalyzers\YAnalyzers\YAnalyzers.Vsix\YAnalyzers.Vsix.csproj]
```

I can reproduce this behavior locally, but only from command-line build.
Building in Visual Studio works.

cc @jmarolf @sharwell

**Comment by Youssef1313** [comment]
Commenting the `Microsoft.VSSDK.BuildTools` package reference fixes the issue:

```xml
<!--<PackageReference Include="Microsoft.VSSDK.BuildTools" Version="15.1.192" PrivateAssets="all" />-->
```

Why is this package needed? Can it be safely removed from the template?

**Comment by sharwell** [comment]
The vsix project does not support building with `dotnet build`. You can either create a solution configuration to exclude it, or create a solution filter (*.slnf) to build instead of the full solution.

**Comment by Youssef1313** [comment]
> The VSSDK build tools package is essential for correct behavior of the project it is installed in.

Can you elaborate more on this? I'm getting the correct behavior without it when I set the Vsix project as the startup project and run it.

**Comment by sharwell** [comment]
In that case, it's running an old version that was installed by a previous build.

**Comment by sharwell** [comment]
I'm going to resolve this one as **wontfix**. It's technically _can't_ fix, but the reason is external to this repository.

**Comment by Youssef1313** [comment]
@sharwell The first issue (building on Linux) (wasn't discussed in comments) can probably have some fix.

**Comment by sharwell** [comment]
@Youssef1313 This was already fixed for dotnet/roslyn-analyzers, so we could use the same approach here.

**Comment by Youssef1313** [comment]
@sharwell Thanks. Opened https://github.com/dotnet/roslyn-sdk/pull/720.
