### ISSUE TITLE
[Question] How to pass AnalyzerConfigOptions when unit testing

### ISSUE THREAD

**Issue by j0shuams** [dotnet/roslyn-sdk#736]
When working on a component of a SourceGenerator, I was writing unit tests to check for diagnostics getting raised on the compilation context created by a source code string. We have a downstream check that [checks a compilation's AnalyzerConfigOptions](https://github.com/microsoft/CsWinRT/blob/173a21e15155e5c7778d44a45829cf14a1d7ff55/src/Authoring/WinRT.SourceGenerator/Helper.cs#L54) for a specified assembly name. When you create a compilation context in a unit test, there's no project file to specify a property AssemblyName, so this check returns null and causes issues. 

[Here](https://github.com/microsoft/CsWinRT/blob/173a21e15155e5c7778d44a45829cf14a1d7ff55/src/Tests/DiagnosticTests/Helpers.cs#L35) is where I do this and would like to pass some kind of `optionsProvider` containing a mapping for "AssemblyName" to something like "TestNamespace", and any other properties we might need. 

Please advise on how I would be able to do this. Let me know if you need more information. 

I'm using these packages:

Microsoft.CodeAnalysis.CSharp.Workspaces, Version="3.8.0-4.20472.6" 
Microsoft.CodeAnalysis.Analyzers, Version="3.3.0"

**Comment by Youssef1313** [comment]
> @Youssef1313 Yes, you can use [Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.XUnit](Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.XUnit) (or equivalent for other language/frameworks).

This is great! May you update the [README](https://github.com/dotnet/roslyn-sdk/blob/master/src/Microsoft.CodeAnalysis.Testing/README.md) for usage examples?
