### ISSUE TITLE
Update test project in analyzer template to .NET Core 3.1

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-sdk#741]
Currently, `<TargetFramework>netcoreapp2.0</TargetFramework>`.

**Comment by sharwell** [comment]
Sure that works

**Comment by Youssef1313** [comment]
This got fixed in https://github.com/dotnet/roslyn-sdk/pull/884. Samples weren't updated though and are still using netcoreapp2.0. Will open a new issue for that.
