### ISSUE TITLE
Default template NuGet.config

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-sdk#742]
It was updated in https://github.com/dotnet/roslyn-sdk/pull/725 to prevent dependency confusion attack.

While the template would build just find, it's unclear what analyzer authors should do for dogfooding.

Analyzers authors obviously don't own dotnet-tools or dotnet-public feeds.

It's also now discouraged to mix public and private feeds.

cc: @mmitche

**Comment by sharwell** [comment]
The template was erroneously updated. I'll work to get it reverted.

**Comment by Youssef1313** [comment]
While there is no problem at all if nuget.org is used with the default template, I think that makes it easier for consumers to make a mistake that makes their project vulnerable.

**Comment by Youssef1313** [comment]
I'm going to close since it the package was uploaded to NuGet.org. Thanks @jmarolf!
