### ISSUE TITLE
.NET Compiler Platform SDK in not compatible with Visual Studio 2017 15.5

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-sdk#75]
@aka-STInG commented on [Tue Dec 05 2017](https://github.com/dotnet/roslyn/issues/23579)

**Version Used**: 
15.5
**Steps to Reproduce**:

1. Open VS after update
2. Windows about incompatible version displayed
3. .NET Compiler Platform SDK is disabled

**Expected Behavior**:
.NET Compiler Platform SDK should work, please provide extension update
**Actual Behavior**:
.NET Compiler Platform SDK is disabled

---

@AdmiralSnyder commented on [Tue Dec 05 2017](https://github.com/dotnet/roslyn/issues/23579#issuecomment-349271869)

is it possible that the ".net compiler platform sdk" is now a component that needs to be (re)installed via visual studio installer rather that being an extension to get from the marketplace?
i saw it was not checked despite having visual studio extension development selected.

---

@AdmiralSnyder commented on [Tue Dec 05 2017](https://github.com/dotnet/roslyn/issues/23579#issuecomment-349272944)

yes, seems so. i uninstalled the package in "Extensions and Updates", and modified the VS installation with the installer selecting ".net compiler platform sdk", and no there is the syntax visualizer again.

---

@shaggygi commented on [Tue Dec 05 2017](https://github.com/dotnet/roslyn/issues/23579#issuecomment-349300583)

I also see this and put in via the VS Send Feedback.

---

@Pilchie commented on [Tue Dec 05 2017](https://github.com/dotnet/roslyn/issues/23579#issuecomment-349354335)

Tagging @jmarolf - this *is* by design, but I wonder if there is something we can do to make the transition easier?  At least updating the marketplace page for the old SDK?

---

@MaStr11 commented on [Wed Dec 06 2017](https://github.com/dotnet/roslyn/issues/23579#issuecomment-349634108)

> But I wonder if there is something we can do to make the transition easier?

In the installation instructions for the [Syntax Visualizer tool](https://github.com/dotnet/roslyn/wiki/Syntax%20Visualizer) a Visual Studio 15.5 section could be added.

---

@Pilchie commented on [Wed Dec 06 2017](https://github.com/dotnet/roslyn/issues/23579#issuecomment-349684227)

Yep - that should help.  @jmarolf - can you take a look at updating that wiki page?

---

@aka-STInG commented on [Thu Dec 07 2017](https://github.com/dotnet/roslyn/issues/23579#issuecomment-349991766)

Thanks for the explanation and solution.
BTW, please support dark theme!

**Comment by jamesqo** [comment]
Any idea when this will be fixed? It's super inconvenient to work without the Syntax Visualizer ☹️

**Comment by sharwell** [comment]
Yesterday I learned that the Syntax Visualizer is part of the VS installer now.

1. Run Visual Studio Installer
2. Hit **Modify**
3. Select the **Individual components** tab
4. Check the box for **.NET Compiler Platform SDK**

It's so un-discoverable that even people who are looking for it specifically by name can't find it.

**Comment by MaStr11** [comment]
I have copied the installation instructions to the readme.md in PR #108.

**Comment by jamaladas** [comment]
It will work if we install from Individual component of Visual studio installer>> Modify as mentioned above by @Sharewell

**Comment by Diaskhan** [comment]
I guesse this issue could be closed! @sharwell  solution is WORK !
