### ISSUE TITLE
It is hard to use test framework for source generators

### ISSUE THREAD

**Issue by naminodarie** [dotnet/roslyn-sdk#754]
from https://github.com/dotnet/roslyn-sdk/issues/602#issuecomment-793645429

It is hard to use test framework for source generators. Some `SourceGeneratorTest<TVerifier>` API are not suitable for source generators.

https://github.com/dotnet/roslyn-sdk/blob/50e2a5526c05033b743d8835a259ca4d8851c441/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.SourceGenerators.Testing/SourceGeneratorTest%601.cs#L61-L79

## It is hard to use `FixedCode`

It is hard to use `FixedCode` because `FixedState.Sources` needs original codes and generated codes.

## `Verify.NotEmpty` should be removed

`Verify.NotEmpty` should be removed. Source generators can work in a project without any C# code like [CsvGenerator](https://github.com/dotnet/roslyn-sdk/blob/50e2a5526c05033b743d8835a259ca4d8851c441/samples/CSharp/SourceGenerators/SourceGeneratorSamples/CsvGenerator.cs). Even if `TestState.Sources` is empty, test can be valid.

## The generated source code is not always deterministic

The generated source code is not always deterministic when the source generator is using `System.Guid`, `System.Random`,`System.DateTime` etc. 

The output can also change due to the indefinite order of `Dictionary<TKey, TValue>` and `ImmutableDictionary<TKey, TValue>`. 

```csharp
private static StringBuilder CreateMetadataSource(StringBuilder sb, ImmutableDictionary<string, string> metadatas)
{
    sb.AppendLine("using System.Reflection;");
    foreach (var p in metadatas)
    {
        sb.Append("[assembly: AssemblyMetadataAttribute(");
        sb.Append(ToLiteral(p.Key));
        sb.Append(",");
        sb.Append(ToLiteral(p.Value));
        sb.AppendLine(")]");
    }
    return sb;
}
```

### Name of source file

Name of genereted file is especially problematic. 

In Windows, name of generated file is `{AssemblyName}\{ClassName}\{hintName}`, but in Mac/Linux, the name is `{AssemblyName}/{ClassName}/{hintName}`.

**Comment by sharwell** [comment]
> It is hard to use FixedCode

In the original comment, you mentioned adding a `GeneratedSources` property. I _really_ like this idea, because it means the entire Source Generator testing approach can be merged with the analyzer testing approach.

Before:

```csharp
await new VerifyCS.Test
{
    TestState =
    {
        Sources =
        {
            @"// Comment",
        },
    },
    FixedState =
    {
        Sources =
        {
            @"{|#0:|}// Comment",
            ("Microsoft.CodeAnalysis.SourceGenerators.Testing.UnitTests\\Microsoft.CodeAnalysis.Testing.TestGenerators.AddEmptyFileWithDiagnostic\\EmptyGeneratedFile.cs", SourceText.From(string.Empty, Encoding.UTF8)),
        },
        ExpectedDiagnostics =
        {
            // /0/Test0.cs(1,1): warning SG0001: Message
            new DiagnosticResult(AddEmptyFileWithDiagnostic.Descriptor).WithLocation(0),
        },
    },
}.RunAsync();
```

After:

```csharp
await new VerifyCS.Test
{
    TestState =
    {
        Sources =
        {
            @"{|#0:|}// Comment",
        },
        GeneratedSources =
        {
            ("Microsoft.CodeAnalysis.SourceGenerators.Testing.UnitTests\\Microsoft.CodeAnalysis.Testing.TestGenerators.AddEmptyFileWithDiagnostic\\EmptyGeneratedFile.cs", SourceText.From(string.Empty, Encoding.UTF8)),
        }
        ExpectedDiagnostics =
        {
            // /0/Test0.cs(1,1): warning SG0001: Message
            new DiagnosticResult(AddEmptyFileWithDiagnostic.Descriptor).WithLocation(0),
        },
    },
}.RunAsync();
```

**Comment by sharwell** [comment]
> Verify.NotEmpty should be removed

This seems fine. If the compiler complains about the lack of source files, the test could just declare that compilation error as an expected diagnostic.

**Comment by sharwell** [comment]
> The generated source code is not always deterministic

I'm not inclined to do anything with the specific goal of making this easier. Determinism is a highly desirable property of source generators. One interim solution would be overriding `SourceGeneratorTest<TVerifier>.GetSourceGenerators()` to construct an instance of the source generator that knows to use specific values in place of its normal non-deterministic values.

**Comment by aetos382** [comment]
If the Source Generator uses StringBuilder.AppendLine, the output will not be deterministic because newline characters are dependent on the Operating System.
Does this mean that using StringBuilder.Append("foo\n") instead of StringBuilder.AppendLine("foo") is the recommended policy for creating a Source Generator?

**Comment by jmarolf** [comment]
@aetos382 I would just construct the expected code state using the platform specific apis like I do [here](https://github.com/jmarolf/generator-start/blob/5c70a4626523490d485b362e34b8136aba3fe129/tests/AutoNotifyGeneratorTests.cs#L110) for path.

**Comment by sharwell** [comment]
I'll create an API and updated tests for `GeneratedSources` so it's clear which direction I envision things going.
