### ISSUE TITLE
Add option to ignore line break diffs in source generators test

### ISSUE THREAD

**Issue by naminodarie** [dotnet/roslyn-sdk#760]
I suggested that I want to test the non-deterministic source code in #754. I understand that testing for non-deterministic source code is certainly complicated. 

But I desire that source generators test to have a special option for line break diffs. https://github.com/dotnet/roslyn-sdk/issues/754#issuecomment-794879530

When using verbatim string literal, the end of line is the file's one.  Probably in Windows, end of line is usually `\r\n`, but in Mac/Linux, is usually `\n`.

```csharp
// Generator
var sb = new System.Text.StringBuilder();
sb.AppendLine();
sb.AppendLine("// 1");
sb.AppendLine("// 1");
var generated = sb.ToString();

// Testing
var expected = @"
// 1
// 2
";

Assert.Equal(expected,generated);  // The test is success?
```

I want this option to default to true because the error message of the end of line diffs is difficult to understand.

For example, I wrote a test https://github.com/naminodarie/roslyn-sdk/commit/c30b7dcb69698a3fcf9fd1f2d6d793c660f15f9a

generated is `"\n// Comment1\n// Comment2"`. expected is `"\r\n// Comment1\r\n// Comment2"`.

>     System.InvalidOperationException : Context: Source generator application
>     content of 'Microsoft.CodeAnalysis.SourceGenerators.Testing.UnitTests\Microsoft.CodeAnalysis.Testing.TestGenerators.AddMultiLineCommentFile\MultiLineCommentGeneratedFile.cs' did not match. Diff shown with expected as baseline:
>      
>      // Comment1
>      // Comment2

**Comment by sharwell** [comment]
This is supported today by writing a custom implementation of `IVerifier` and using that instead of one of the standard verifiers. Since deterministic output is a goal (or strong recommendation), it's unlikely that we would be making changes to specifically accommodate non-deterministic outputs.

**Comment by kadamgreene** [comment]
I really thing this needs to be revisited.  If you are using git, the line ending processing will make tests fail / running tests created on Windows on  Linux machine, etc.  I understand the desire for deterministic output, but if you could make it easier for those of us that don't care to verify our code, that would be great.

**Comment by kadamgreene** [comment]
I looked into the current source code, and your instruction to create a custom IVerifier is incorrect.  The offending code is in an extension method, and is not possible to override / reimplement (as there are no methods on IVerifier that are actually called)
