### ISSUE TITLE
Test fails when SourceGeneratorTest<TVerifier>.TestState.Sources depends on generated source code

### ISSUE THREAD

**Issue by naminodarie** [dotnet/roslyn-sdk#762]
**Steps to Reproduce**:

https://github.com/dotnet/roslyn-sdk/commit/c2ab23949618c08b001195226e4134473df89937

SourceGeneratorTest<TVerifier>.TestState.Sources depends on generated source code.

```csharp
using System;
using System.Collections.Generic;
using System.Text;

namespace Microsoft.CodeAnalysis.Testing.TestGenerators
{
    public class AddSimpleAttribute : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
        }

        public virtual void Execute(GeneratorExecutionContext context)
        {
            context.AddSource("SimpleAttribute", "using System;[AttributeUsage(AttributeTargets.All)] internal sealed class SimpleAttribute : Attribute { }");
        }
    }
}
```

```csharp
await new CSharpSourceGeneratorTest<AddSimpleAttribute>
{
    TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck,
    TestState =
    {
        Sources =
        {
            @"[Simple]class S {}",
        },
        GeneratedSources =
        {
            (typeof(AddSimpleAttribute), "SimpleAttribute.cs", "using System;[AttributeUsage(AttributeTargets.All)] internal sealed class SimpleAttribute : Attribute { }"),
        },
    },
}.RunAsync();
```

**Expected Behavior**:

Success

**Actual Behavior**:

>     System.InvalidOperationException : Context: Diagnostics of test state
>     Mismatch between number of diagnostics returned, expected "0" actual "2"

Adding diagnostics to ExpectedDiagnostics will solve the problem, but it is different from the actual compilation result.

**Comment by sharwell** [comment]
This should have been fixed by https://github.com/dotnet/roslyn-sdk/pull/776. Can you try updating the library and check again?

**Comment by naminodarie** [comment]
Great! I want this behavior!

**Comment by sharwell** [comment]
@naminodarie Note that this line completely disables validation for your source generator:

```
TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck,
```

You'll want to remove this line and just use the default behaviors.

**Comment by naminodarie** [comment]
@sharwell Thank you for your advice!
