### ISSUE TITLE
No reference assemblies for net5.0

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn-sdk#771]

**Comment by sharwell** [comment]
Can you provide more details?

https://github.com/dotnet/roslyn-sdk/blob/33aaf1d72965733b7816b278c6ea2d594a9199d7/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs#L849-L869

**Comment by agocke** [comment]
Huh, I don't see that in the list. I have version `1.0.1-beta1.21177.1` of Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.Xunit. Is there something newer?

**Comment by agocke** [comment]
Ah, nvm, I see the problem, I was looking in `NetCore`. Would it be worth it to add an alias to netcore? This is what nuget does (`netcoreapp5.0 == net5.0`)
