### ISSUE TITLE
Update dependencies for .NET Core/.NET 5.0

### ISSUE THREAD

**Issue by dlech** [dotnet/roslyn-sdk#793]
I tried writing an analyzer in VS Code on Mac using .NET 5.0. It seems to work. The analyzer project is targeting `netstandard2.0` as in the sample project in this repo but the test project is targeting `net5.0` since OmniSharp only supports debugging with the .NET Core debugger.

Even though everything seems to be working, restoring the NuGet packages gives the following warnings:

```
/Users/david/work/gisharp/test/Test.Analyzers/Test.Analyzers.csproj : warning NU1701: Package 'Microsoft.CodeAnalysis.CSharp.Workspaces 1.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
/Users/david/work/gisharp/test/Test.Analyzers/Test.Analyzers.csproj : warning NU1701: Package 'Microsoft.CodeAnalysis.Workspaces.Common 1.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
/Users/david/work/gisharp/test/Test.Analyzers/Test.Analyzers.csproj : warning NU1701: Package 'Microsoft.Composition 1.0.27' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
```

It looks like the depedency is coming from here:

https://github.com/dotnet/roslyn-sdk/blob/8835cb7ef3de5d76b43874f091346e56c37ce912/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CSharp.Analyzer.Testing.NUnit/Microsoft.CodeAnalysis.CSharp.Analyzer.Testing.NUnit.csproj#L18

Would it be possible to bump the `Microsoft.CodeAnalysis.CSharp.Workspaces` dependency to something newer so that NuGet won't complain?

**Comment by jmarolf** [comment]
@sharwell

**Comment by sharwell** [comment]
@dlech You can reference any newer version of `Microsoft.CodeAnalysis` to avoid this (the library supports testing against any version of Roslyn that you select).
