### ISSUE TITLE
[Question] Debug Roslyn Analyzers with IsRoslynComponent

### ISSUE THREAD

**Issue by TwentyFourMinutes** [dotnet/roslyn-sdk#801]
Since we are now able to Debug Source Generators, by simply adding `<IsRosyComponent>true</IsRosyComponent>`, I was curious, if there will be/is any way to do the same with Roslyn Analyzers, since debugging them through VSIX is really painful.

**Comment by jmarolf** [comment]
cc: @chsienki

**Comment by chsienki** [comment]
This should work today for analyzers too, in the same way as generators. Have you tried it and hit issues?

**Comment by TwentyFourMinutes** [comment]
I actually gave it a shot, just in the same way as you would with Source Generators, but the break point "just would not hit". However, while trying again today, it seemed to work like a charm. 👍

**Comment by chsienki** [comment]
Great to hear. Feel free to re-open this if you're still having issues with breakpoints not hitting in the future.
