### ISSUE TITLE
Add API to Microsoft.CodeAnalysis.SourceGenerators.Testing to allow for providing GlobalOptions 

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-sdk#823]
see example here: https://github.com/jmarolf/generator-start/pull/11

would be nice if the user could provide a set of global options for testing.

CC: @sharwell

**Comment by sharwell** [comment]
This API was added in #734

**Comment by jmarolf** [comment]
The intent here is for people who want to test consumption of [MSBuild Properties](https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#consume-msbuild-properties-and-metadata). Should probably probably update this to make that clear. Someone could specify this information via editorconfig files but if the intent is to check an msbuild property what do we recommend?

**Comment by sharwell** [comment]
MSBuild properties are injected via a global config, so it would be tested using `AnalyzerConfigFiles` with this format:

```
is_global = true

// properties here
```
