### ISSUE TITLE
After installing .NET Compiler Platform SDK in VS 2017(15.3.2), "Roslyn Syntax Visualizer" is not visible in the "Other Windows" list.

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-sdk#83]
@namkilee commented on [Fri Aug 25 2017](https://github.com/dotnet/roslyn/issues/21735)

**Version Used**: 
* Visual Studio ( 15.3.2 )
![image](https://user-images.githubusercontent.com/5918184/29712064-ea53c44e-89d2-11e7-97be-6456c2af4436.png)
* .NET Compiler Platform SDK ( 2.0.0.6140902 )
![image](https://user-images.githubusercontent.com/5918184/29712084-092512ce-89d3-11e7-9bae-773cc7f8ae3f.png)

**Steps to Reproduce**:
https://github.com/dotnet/roslyn/wiki/Syntax%20Visualizer
1.  .NET Compiler Platform SDK extension install in Visual Studio 2017 Marketplace
2.  Create C# Project using Project Wizard ( C# Console Application .NET Framework )
3.  To launch Syntax Visualizer : View -> Other Windows -> Roslyn Syntax Visualizer
4. Check Other Windows list.

**Expected Behavior**:
Exist "Roslyn Syntax Visualizer" in "Other Windows" list 
**Actual Behavior**:
Not exist
![image](https://user-images.githubusercontent.com/5918184/29712254-f2fbe404-89d3-11e7-9eb4-f7b6244d85cd.png)

---

@tanveerbadar commented on [Wed Aug 30 2017](https://github.com/dotnet/roslyn/issues/21735#issuecomment-326181363)

Same for me.

---

@brandonr1 commented on [Thu Aug 31 2017](https://github.com/dotnet/roslyn/issues/21735#issuecomment-326297380)

I had the same issue, I ran update 15.3.3 and it resolved the problem.

---

@Pilchie commented on [Thu Sep 07 2017](https://github.com/dotnet/roslyn/issues/21735#issuecomment-327823659)

@jmarolf ?

---

@jmarolf commented on [Thu Sep 07 2017](https://github.com/dotnet/roslyn/issues/21735#issuecomment-327847116)

@namkilee are you able to use the templates installed with the SDK? I can't reproduce this on my 15.3 machine

---

@namkilee commented on [Sun Sep 10 2017](https://github.com/dotnet/roslyn/issues/21735#issuecomment-328398088)

@jmarolf 
Yes, I able to use the template "Analyzer with Code Fix".
However, the menu was still invisible. 
So I reinstalled VS, confirmed that the problem was fixed after the update.
Maybe I have a problem with my machine.

---

@nathvi commented on [Wed Dec 20 2017](https://github.com/dotnet/roslyn/issues/21735#issuecomment-353191128)

This is not fixed. Who closed this issue.

**Comment by nathvi** [comment]
This is not fixed.

**Comment by jmarolf** [comment]
@nathvi in 15.5 the syntax visualizer was moved into the VS installer.  
![image](https://user-images.githubusercontent.com/9797472/34313002-f21dcf60-e71c-11e7-8965-3a6db877efe3.png)
after installing the syntax visualizer should be there.  Is that not happening for you?

**Comment by MarkusAmshove** [comment]
I had the same issue has @nathvi 

I just uninstalled the extension and added `.NET Compiler Platform SDK` via the VS installer and now I have the syntax tree 👍

**Comment by jmarolf** [comment]
@nathvi  can you confirm this works for you?

**Comment by nathvi** [comment]
I used the Visual Studio installer and installed the `.NET Compiler Platform SDK`, I now have the syntax tree as well.  Thanks for the workaround.

**Comment by nathvi** [comment]
@jmarolf
