### ISSUE TITLE
Nothing in Microsoft.CodeAnalysis.Analyzer.Testing has been shipped

### ISSUE THREAD

**Issue by arturohernandez10** [dotnet/roslyn-sdk#838]
I am trying to write a test for a `DiagnosticAnalyzer` which will hold properties to be used by a CodeFix. I wanted to make sure I have the right properties and I intend to use the Microsoft.CodeAnalysis.Analyzer.Testing code.

In particular I am thinking of using the `CSharpAnalyzerTest.DiagnosticVerifier` property. So I can match property values returned by the analyzer. This is just exploratory code, but it illustrates how I could possibly use it. 

```
    public class PatternTest : CSharpAnalyzerTest<PatternUsageAnalyzer, XUnitVerifier>
    {
        public PatternTest()
        {
            // somehow we have to subclass DiagnosticResult and include the expected values. so that the properties can be matched too.
            DiagnosticVerifier = (Diagnostic diagnostic, DiagnosticResult result, IVerifier verifier) =>
            {
                verifier.Equal(diagnostic.Properties.Count, result.MessageArguments?.Length ?? 0, "Same number of messages as properties");
            };
        }

        [Fact]
        public async Task DiagnosesPatternUsage()
        {
            TestCode = Fixture.Correct;

            ExpectedDiagnostics.Add(
                new DiagnosticResult(Descriptors.PG0001ExceptionNameFormat.Id, DiagnosticSeverity.Hidden)
                    .WithArguments(/*properties????*/));

            await RunAsync();
        }
    }
```

Even if the API changes, the code surface is so minimal that refactoring should not hurt the code much. Is there a reason why nothing has been marked as Shipped??

**Comment by sharwell** [comment]
@jmarolf has now published the 1.1.0 release to GitHub.
