### ISSUE TITLE
Publish Microsoft.CodeAnalysis.VisualBasic.SourceGenerators.Testing.XUnit to test source generators with an VisualBasicCompilation in C# unit tests.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/roslyn-sdk#859]
Currently on my unit tests for my own source generator (to test bailing out of it) I have to do some hacking to do something similar.

As such I think I would like the testing library to contain this specific class to help simplify unit testing of source generators so they do not have to use GeneratorDriver classes specific to each language (C# or VB only currently) to do the same thing.

Some source generators also do custom generating logic for Visual Basic as well when it detects that it's installed in a VB project.

https://github.com/Elskom/GitBuildInfo.SourceGenerator/pull/37/files#diff-ab1f9e3ecaca5cd97cca73352bd17f37fe90532fbae37f11008c94b787e1dfa9R96-R107
https://github.com/Elskom/GitBuildInfo.SourceGenerator/pull/37/files#diff-ab1f9e3ecaca5cd97cca73352bd17f37fe90532fbae37f11008c94b787e1dfa9R96-R107

That code could be simplified drastically to be similar to how I do it with the C# class to test the generator without ever touching the GeneratorDriver class for C# myself.

**Comment by AraHaan** [comment]
It seems this does exist but when trying to utilize that package it won't resolve it currently:

``error NU1101: Unable to find package Microsoft.CodeAnalysis.VisualBasic.SourceGenerators.Testing.XUnit. No packages exist with this id in source(s): nuget.org, xunit-prereleases``

**Comment by jmarolf** [comment]
[done](https://www.nuget.org/packages/Microsoft.CodeAnalysis.VisualBasic.SourceGenerators.Testing.XUnit/)
