### ISSUE TITLE
Cannot debug or install new Analyser with Codefix

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-sdk#86]
When I create a new Code-Analyser with codefix, the creation of the project works properly.

But if I want to debug just the default given analyser rule, the Visualstudio debug instance does not highlight any errors or warning, but the analyser does report a diagnostic warning indeed.

And if I try to install the generated vsix, I get a "manifest file is invalid"

This just happend after the update to 15.5. 
-----------------------------------------------------------------------------------------------------------------
follow-up from  Dirk Lehmeier 

I just made a new Code-Analysis Test Project and now the vsix installer worked.

But I found out the problem while debugging the code analyis rule:

The projectfile didn't had any <CodeAnalysisRuleSet> element. Even if Visual Studio shows MinimumRecommendedRules in the project settings. Then the attached debugger will step into the analysis rule an reports an error, but Visual Studio does not highlight anything.

If I switch the ruleset in the project settings and switch back to MinimumRecommendedRules I will get the entry in my project file:

<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>

and Visual Studio will highlight the diagnostics.

**Comment by sharwell** [comment]
The analyzer templates have since been rewritten and should be working again.
