### ISSUE TITLE
Add reference assemblies for net6.0-[platform] TFMs

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-sdk#892]
https://github.com/dotnet/designs/blob/main/accepted/2021/net6.0-tfms/net6.0-tfms.md#design

**Comment by Youssef1313** [comment]
@sharwell Is this possible? If yes, it would be nice to have :)

**Comment by jmarolf** [comment]
So the ask is to have `Net60Windows`, `Net60Android`, etc in addition to `Net60` like we have here?

https://github.com/dotnet/roslyn-sdk/blob/b7df823f6a23d8fb316c8ee2c25237df7c151123/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs#L887

I have no problem with that, but it would require there to be nuget packages with these references. Currently we rely on [Microsoft.NETCore.App.Ref](https://www.nuget.org/packages/Microsoft.NETCore.App.Ref).

This is my best understanding of the reference nuget packages and how they map. Once this is filled out all the way implementing the API should be straightforward.

| Property Name | Nuget Package |
|:--------------|---------------|
|`Net60Windows` | [Microsoft.WindowsDesktop.App.Ref](https://www.nuget.org/packages/Microsoft.WindowsDesktop.App.Ref)
| `Net60Android` | ???
| `Net60iOS` | ???
| `Net60MacOS` | ???
| `Net60MacCatalyst` | ???
| `Net60TvOS` | ???
| `Net60Tizen` | ???

**Comment by Youssef1313** [comment]
@jmarolf Yes that's exactly what I'm asking for.
I'm not sure whether there are NuGet packages for these or not. But the lack of these reference assemblies makes testing analyzers/generators that are very domain-specific in these areas nearly impossible.

**Comment by Youssef1313** [comment]
@jmarolf Thanks!! That was too fast :)
