### ISSUE TITLE
Validate code fix output text matches the expected text before trying to validate the tree structure

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-sdk#924]
It seems like it would be beneficial to validate that the code fix output text matches the expected text _before_ trying to validate the tree structure. The problem would have been obvious for you if it used that order.

_Originally posted by @sharwell in https://github.com/dotnet/roslyn-sdk/issues/919#issuecomment-943743358_

**Comment by CyrusNajmabadi** [comment]
Yes plz... i often start with a copy of another test.  i just want to run the test and determinet he new baseline prior to any other analysis of the fixed state.
