### ISSUE TITLE
Visual Studio Extension Development should automatically include the .NET Compiler Platform SDK component

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn-sdk#927]
Selecting Visual Studio Extension Development should automatically include the .NET Compiler Platform SDK component. 
 
![image](https://user-images.githubusercontent.com/46729679/139730819-7ac40179-796e-4c85-9075-b7bc6d3a5f48.png)

**Comment by jmarolf** [comment]
internal pull request to fix this [here](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/361710)

**Comment by jmarolf** [comment]
The internal setup PR has been merged and will be available in VS 2022 17.1 Preview 2
