### ISSUE TITLE
Update samples to include how to use IIncrementalGenerator

### ISSUE THREAD

**Issue by musictopia2** [dotnet/roslyn-sdk#933]
I have managed to create some source generators that implement the ISourceGenerator interface.

I found that .net 6 has the new interface IIncrementalGenerator which can help improve performance.

However, I found that the information being sent is not nearly as much as the ISourceGenerator.
So a person has to do something completely different in order to get the information needed to even produce strings.

**Comment by sharwell** [comment]
Duplicate of #941

**Comment by sharwell** [comment]
@musictopia2 this issue was reported first, but I marked it as a duplicate because I answered the other issue first. 😄
