### ISSUE TITLE
Specified `Microsoft.VsSDK.BuildTools` version in templates doesn't work with VS 2022

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-sdk#934]
https://github.com/dotnet/roslyn-sdk/blob/e7e67fa7343cc528dbc843653d4345d78f0870df/src/VisualStudio.Roslyn.SDK/Roslyn.SDK/ProjectTemplates/CSharp/CodeRefactoring/Vsix/Deployment.csproj#L22

![image](https://user-images.githubusercontent.com/31348972/145563154-a9480269-5a3b-4a55-b822-df4c69c89ec1.png)

This doesn't seem to be working for VS 2022. I don't know of an MSBuild property to determine VS version and use different versions accordingly.

cc @sharwell

**Comment by sharwell** [comment]
> This doesn't seem to be working for VS 2022

Can you provide more detail for this? This repository has integration tests that create a project from this template inside Visual Studio 2022, and then build that project and verify that there are no build errors.

**Comment by Youssef1313** [comment]
@sharwell There is a small screenshot of the error in the issue. It's from a brand new analyzer + codefix project and it gets fixed after updating this package.

**Comment by sharwell** [comment]
The image shows version 15.1.192, so I'm guessing it was created with templates prior to https://github.com/dotnet/roslyn-sdk/commit/10e46ded6da69c7affecf727d54e2a87d9695c15 and has already been fixed.

**Comment by Youssef1313** [comment]
> Small is correct.

I should have copied the error. 😄 

----

Yup it seems before the commit you mentioned. Closing. Thanks for the quick response @sharwell!

**Comment by sharwell** [comment]
This was already fixed in #884 🎉
