### ISSUE TITLE
Add support for `IIncrementalGenerator`

### ISSUE THREAD

**Issue by Flash0ver** [dotnet/roslyn-sdk#941]
For `ISourceGenerator` that were introduced in `3.8`, I was able to adopt the `Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.[Test-Framework]` package quickly, since I'm also familiar with the `Analyzer`/`CodeFix`/`CodeRefactoring` variants.

Now I would love to see an `IncrementalGenerators` variant.
An alternative would be to add support for `IIncrementalGenerator` to the already existing `SourceGenerators` package, but I guess this is not preferable since the update of the dependency `Microsoft.CodeAnalysis.CSharp.Workspaces` to `4.0.1` would be a breaking change for existing consumers.

I built a custom testing helpers (inspired by the [Source Generators Cookbook](https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#unit-testing-of-generators)), which are continuously growing (across my source generator projects), but are missing the really powerful features such as `ReferenceAssemblies` and `{|#0:Location|}`-Syntax.

I also noticed #933, but if I understand correctly, then `IIncrementalGenerator` are not suppored by `Microsoft.CodeAnalysis.Testing`, because the generic `CSharpSourceGeneratorVerifier` and `CSharpSourceGeneratorTest` types are constrained to `ISourceGenerator, new()`.
I also tried to apply the `ISourceGenerator`-types from _Microsoft.CodeAnalysis.Testing_, and then use `CSharpSourceGeneratorTest` with a custom _IncrementalGenerator-to-SourceGenerator-wrapper_. But this approach failed, because the methods of the instance returned by [Microsoft.CodeAnalysis.GeneratorExtensions.AsSourceGenerator()](https://sourceroslyn.io/#Microsoft.CodeAnalysis/SourceGeneration/GeneratorExtensions.cs) throw an `InvalidOperationException` with message `This program location is thought to be unreachable.`. I have just learnt that the `CSharpGeneratorDriver` unwraps that type again and does not use it directly.
Here's a link this failed experiment: https://github.com/Flash0ver/F0.Compatibility/blob/test/microsoft-codeanalysis-testing/src/tests/F0.Compatibility.Generator.Tests/Testing/CSharpIncrementalGeneratorVerifier.Test.cs

**Comment by sharwell** [comment]
Here are the two verifier classes for an incremental generator:
https://github.com/tunnelvisionlabs/language-types/blob/main/test/TunnelVisionLabs.LanguageTypes.SourceGenerator.UnitTests/Verifiers/CSharpSourceGeneratorVerifier%601.cs
https://github.com/tunnelvisionlabs/language-types/blob/main/test/TunnelVisionLabs.LanguageTypes.SourceGenerator.UnitTests/Verifiers/CSharpSourceGeneratorVerifier%601%2BTest.cs

**Comment by Flash0ver** [comment]
Great! Thank you! I'll try it out over next weekend.

**Comment by Flash0ver** [comment]
And I got my `IIncrementalGenerator` tests running.

I didn't know about the combination of
- `EmptySourceGeneratorProvider` for our `CSharpSourceGeneratorTest` derivation
- overriding `GetSourceGenerators()` so that we can `AsSourceGenerator()` the `IIncrementalGenerator` under test

Thank you very much @sharwell for the example!

**Comment by AraHaan** [comment]
I think it should now be safe to use 4.0.1 on Microsoft.CodeAnalysis.CSharp.Workspaces due to .NET 6 LTS and .NET 5 being close to EOL. Besides I do not think many are using the .NET 5 SDK anymore and are instead using the .NET 6 or newer SDK and targeting .NET 5 making it able to use generators using v4.0.1 of the roslyn packages without issues because they will be using a newer compiler that uses those versions anyway.
