### ISSUE TITLE
Improve support for `DiagnosticSuppressor`

### ISSUE THREAD

**Issue by Flash0ver** [dotnet/roslyn-sdk#942]
I just tried writing unit tests for a [DiagnosticSuppressor](https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticSuppressor.cs) via `Microsoft.CodeAnalysis.Testing`, but I have not succeeded.
Although `DiagnosticSuppressor` does derive from [DiagnosticAnalyzer](https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalyzer.cs), and with that already inheriting support in the available infrastructure of `Microsoft.CodeAnalysis.Testing`, I was still unable to get it working.

My approach was to always add a custom `DiagnosticAnalyzer` which reports all diagnostics defined in the Assert-Phase of the test through a custom collection of [DiagnosticResult](https://github.com/dotnet/roslyn-sdk/blob/main/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/DiagnosticResult.cs)s.
After this Testing-Internal `DiagnosticAnalyzer` has reported all arranged diagnostics, the `DiagnosticSuppressor` under test could then suppress these, so that there are no `ExpectedDiagnostics` left.
But I couldn't really get the _Markup_-Syntax working, nor manually setting the _Location_/_Span_ of the arranged diagnostic(s) to be suppressed during the Act-Phase, so that the Assert-Phase can expect zero `ExpectedDiagnostics`, or at least a set of `ExpectedDiagnostics` without the previously reported and suppressed `DiagnosticResult`s. Maybe I got something wrong with the _Location_/_TextSpan_/_Path_: the `DiagnosticSuppressor` did receive the `ReportedDiagnostics`, but even after invoking `ReportSuppression` the test still failed with the message "`Mismatch between number of diagnostics returned, expected "0" actual "1"`".

Perhaps adding such a `DiagnosticResult`-Collection to the ``AnalyzerTest`1`` or `ProjectState` (or another suitable type), which is iterated and diagnostics produced from, which are then subject to be passed to the `DiagnosticSuppressor` under test if supported, would be of great benefit for all authors of analyzers utilizing the might of `Microsoft.CodeAnalysis.Testing`.
I guess there is also a different perhaps more intuitive approach to be discussed.

**Comment by sharwell** [comment]
I was expecting this to be fixed by https://github.com/dotnet/roslyn-sdk/pull/917. Have you had a chance to try this functionality out?

**Comment by Flash0ver** [comment]
Thank you @sharwell for the hint. I tried it out and it worked perfectly.
Thank you @tom-englert for the implementation and the great example!
