### ISSUE TITLE
Is the Syntax Visualizer extenions gone in Visual Studio v.7.0.5?

### ISSUE THREAD

**Issue by Corniel** [dotnet/roslyn-sdk#951]
The Syntax Visualizer extension seems to be gone. It not available in the extension manager, nor available in the menu. Am I doing something wrong, or is the nice feature been dropped?

**Comment by sharwell** [comment]
It's now part of the Visual Studio installer. See https://github.com/dotnet/roslyn-sdk/issues/83#issuecomment-353678239 for an example.
