### ISSUE TITLE
Duplicate item template IDs

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn-sdk#97]
Item templates defined in .vstemplate files in the following subtree have identical 'Microsoft.CSharp.Class' 'TemplateId' fields, leading to ambiguity when it comes to loading templates by name in the Visual Studio template engine.

This ambiguity causes an Apex test failure in VSUVSCORE during an 'Add Item' scenario because the incorrect template gets loaded by name and added to the solution. See [DEVDIV Bug](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=563024).

There is as of yet no known user-facing impact, however, this is known to break DTE scenarios and scenarios that attempt to add a Microsoft.CSharp.Class template by name.

Based on commit history, it looks like the test failure just started appearing either due to a templates change in this repository (all [item templates](https://github.com/dotnet/roslyn-sdk/tree/ca4facfd43e724f7116fe52fa25a24826ae7a2ae/src/Templates) appear to have been created within the last 4 months) or by [this change](https://devdiv.visualstudio.com/DevDiv/Editor/_git/VS/pullrequest/95932) to the template engine, which may have somehow changed the order in which we attempt to match templates (affected code lives in newtree.cpp).

Best fix is to give each template a unique ID that corresponds to the feature and purpose.

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn-sdk/pull/101
