### ISSUE TITLE
ArgumentNullException from NuGet calls in Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/roslyn-sdk#974]
We recently hit an `ArgumentNullException` that stemmed from us using the `ReferenceAssemblies` API in dotnet/runtime. This occurred in https://github.com/dotnet/runtime/pull/66952 on macOS x64 ([Helix Log here](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-66952-merge-bbd9bbac458c42438b/LibraryImportGenerator.Unit.Tests/1/console.d33f14e2.log?sv=2019-07-07&se=2022-04-10T19%3A36%3A01Z&sr=c&sp=rl&sig=vd2BMsqzgNVoC6OWpbIb4XbkmqAOww9ZmTzn9SbzShU%3D)).

This looks like it may have been a one-off failure, but I wanted to report it in case it's reproducible as even one-off-style failures can cause significant issues keeping dotnet/runtime green.

**Comment by jkoritzinsky** [comment]
Another hit in https://dev.azure.com/dnceng/public/_build/results?buildId=1674834&view=ms.vss-test-web.build-test-results-tab&runId=45943994&resultId=151060&paneView=debug, so this isn't a one-off.

cc: @sharwell

**Comment by jkoritzinsky** [comment]
We're hitting this pretty often in dotnet/runtime, so it's definitely not a one-off failure.

**Comment by danmoseley** [comment]
This is now happening 10x a day in dotnet/runtime   @jaredpar @sharwell could someone please take a look?


```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= now(-2d)
| where Result == "Fail"
| where Message startswith "System.ArgumentNullException : Value cannot be null. (Parameter 'package"
| project Type, Method,
  Pipeline = tostring(parse_json(Properties).DefinitionName),//WorkItemFriendlyName,
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
 Finished,
 Build
```

|Type|Method|Pipeline|Pipeline_Configuration|OS|Arch|Finished|Build|
|---|---|---|---|---|---|---|---|
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|ubuntu.1804.amd64.open.rt|x64|2022-04-03 05:47:00.2100000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-03 11:07:44.0470000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-03 11:45:31.8160000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-03 13:10:04.4850000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-03 14:21:22.3510000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-03 14:49:27.0420000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-03 15:00:33.7380000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-03 15:00:40.0250000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-03 15:32:33.8270000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-03 17:41:13.1510000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-03 21:28:47.8030000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-03 21:29:03.7300000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-03 21:38:53.4540000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-04 07:38:32.3100000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Release|osx.1200.amd64.open|x64|2022-04-04 08:49:46.4760000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-04 09:40:50.5660000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-04 10:20:12.4610000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-04 10:32:02.6900000||
|LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub|SkipLocalsInitOnDownlevelTargetFrameworks|runtime|Debug|osx.1200.amd64.open|x64|2022-04-04 15:17:13.2330000||
