### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.XUnit fails for tests targeting net5.0+

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-sdk#978]
When trying to add a `net6.0` target to my analyzer tests, I found they mostly failed with this exception:

```
// error CS1705: Assembly 'Microsoft.VisualStudio.Threading' with identity 'Microsoft.VisualStudio.Threading, Version=17.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

The test project created by the analyzer test framework (with my configuration) includes a reference to MS.VS.Threading, which includes a net5.0 target. When my test project targets net5.0 or later, it'll find and use the net5.0 target of vs-threading in the analyzer synthesized test 'project'. But the Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.XUnit project only includes `netcoreapp3.1` references at the latest, leading to a conflict between System.Runtime versions. 

For now, I just replaced my `net6.0` test project target with netcoreapp3.1. But as net6.0 the more relevant target nowadays, I'd like to verify that my analyzers run properly on it rather than a much older runtime.

**Comment by AArnott** [comment]
CC: @sharwell

**Comment by sharwell** [comment]
Is this a failure to compile the test project, or a failure to run a test?

**Comment by AArnott** [comment]
The test project compiles fine. The test fails to run.

**Comment by sharwell** [comment]
Can you link me to a test with this behavior?

**Comment by AArnott** [comment]
```
git clone https://github.com/AArnott/vs-threading.git
cd vs-threading
git checkout TestAnalyzersOnNet5.0
dotnet test .\test\Microsoft.VisualStudio.Threading.Analyzers.Tests
```

You'll see all tests pass on net472 and netcoreapp3.1, and most fail on the net5.0-windows one for the reasons described in the issue description.

**Comment by sharwell** [comment]
It looks like the tests use `ReferenceAssemblies.Default`:

https://github.com/AArnott/vs-threading/blob/127e17de4f30fc1b380426f65f069891973e1406/test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/ReferencesHelper.cs#L12

This should be updated to use the reference assemblies for a specific target framework. For example, you could rewrite the constructor for `ReferencesHelper` like this:

```
        static ReferencesHelper()
        {
#pragma warning disable RS0030 // Do not used banned APIs
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
#pragma warning restore RS0030 // Do not used banned APIs

#if NET472
            ReferenceAssemblies frameworkDefault = ReferenceAssemblies.NetFramework.Net472.Default;
#elif NETCOREAPP3_1
            ReferenceAssemblies frameworkDefault = ReferenceAssemblies.NetCore.NetCoreApp31;
#elif NET5_0
            ReferenceAssemblies frameworkDefault = ReferenceAssemblies.Net.Net50;
#endif
            DefaultReferences = frameworkDefault
                .WithPackages(ImmutableArray.Create(
                    new PackageIdentity("System.Collections.Immutable", "5.0.0"),
                    new PackageIdentity("System.Threading.Tasks.Extensions", "4.5.4"),
                    new PackageIdentity("Microsoft.Bcl.AsyncInterfaces", "6.0.0")));
        }
```
