### ISSUE TITLE
Source Generator XUnit references CodeAnalysis package conflicts 4.1.0 version

### ISSUE THREAD

**Issue by buzzers** [dotnet/roslyn-sdk#982]
`Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.XUnit` v1.1.1 references `Microsoft.CodeAnalysis.CSharp.Workspaces` old v3.8.0 version.

I found an issue (#891) related. However, according to its description, I references the new version of the package ( v4.1.0 ) is referenced in my test project, but the compilation still fails.

Do I have to use v3.8.0, or is there another workaround?

**Comment by sharwell** [comment]
3.8.0 is the minimum version. You can explicitly reference a newer version of Microsoft.CodeAnalysis to use a specific version in tests.

**Comment by buzzers** [comment]
@sharwell 

1. Open a command shell, and Run the following commands:

```csharp
dotnet new xunit -o sourcegenerator-xunit
cd sourcegenerator-xunit
dotnet add package Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.XUnit
```

2. Try add v4.1.0 package

```csharp
dotnet add package Microsoft.CodeAnalysis.CSharp
```

and I get error `error: NU1107`.

3. Add `Microsoft.CodeAnalysis.Common` v4.1.0

```csharp
dotnet add package Microsoft.CodeAnalysis.Common
```

I get a warn `warn : NU1608`, and then retry add `Microsoft.CodeAnalysis.CSharp`, get warn `warn : NU1608`.

After manually referencing the `Microsoft.CodeAnalysis.Common` package, the test can be successfully run, but there will be a warning `NU1608`. Is this no problem, how to eliminate it?

**Comment by sharwell** [comment]
> ```
> dotnet add package Microsoft.CodeAnalysis.CSharp
> ```

This line is the problem. To bring in the full set of dependencies with the higher version, you need to do this:

```
dotnet add package Microsoft.CodeAnalysis.CSharp.Workspaces
```

**Comment by buzzers** [comment]
@sharwell 
It's working fine now, thanks.
